In [7]:
import pandas as pd

# قراءة الملفات
df_shooting = pd.read_csv(r"C:\Users\Access\Documents\AI ROBOT\XAUUSD_5m_trade_result_shooting.csv")
df_hammer = pd.read_csv(r"C:\Users\Access\Documents\AI ROBOT\XAUUSD_5m_trade_result_hammer.csv")

# دمج DataFrame‌ين
df_combined = pd.concat([df_shooting, df_hammer])

# تجميع البيانات بناءً على عمود trade_type وجمع القيم في الأعمدة المطلوبة
df_merged = df_combined.groupby('Unnamed: 0', as_index=False).agg({
    'Losing Trades': 'sum',
    'Winning Trades': 'sum',
    'Total Trades': 'sum'
})

# عرض النتيجة
print(df_merged)

      Unnamed: 0  Losing Trades  Winning Trades  Total Trades
0     2020-01-01              0               0             0
1     2020-01-02              0               6             6
2     2020-01-03              0               4             4
3     2020-01-06              1               2             3
4     2020-01-07              0              11            11
...          ...            ...             ...           ...
1300  2024-12-25              0               0             0
1301  2024-12-26              0               4             4
1302  2024-12-27              1               3             4
1303  2024-12-30              0              10            10
1304  2024-12-31              2               9            11

[1305 rows x 4 columns]

In [9]:
# تغيير اسم العمود الأول من 'Unnamed: 0' إلى اسم جديد (مثلاً 'ID')
df_merged.rename(columns={'Unnamed: 0': 'Date'}, inplace=True)

In [10]:
df_merged

            Date  Losing Trades  Winning Trades  Total Trades
0     2020-01-01              0               0             0
1     2020-01-02              0               6             6
2     2020-01-03              0               4             4
3     2020-01-06              1               2             3
4     2020-01-07              0              11            11
...          ...            ...             ...           ...
1300  2024-12-25              0               0             0
1301  2024-12-26              0               4             4
1302  2024-12-27              1               3             4
1303  2024-12-30              0              10            10
1304  2024-12-31              2               9            11

[1305 rows x 4 columns]

In [11]:
df_merged.describe().round(1).drop(['count','std'])

      Losing Trades  Winning Trades  Total Trades
mean            1.2             4.6           5.8
min             0.0             0.0           0.0
25%             0.0             3.0           4.0
50%             1.0             5.0           6.0
75%             2.0             6.0           8.0
max             6.0            13.0          14.0

In [12]:
daily_trades = df_merged

# حساب التكرارات والنسب المئوية
total_counts = daily_trades['Total Trades'].value_counts()
total_percent = daily_trades['Total Trades'].value_counts(normalize=True) * 100

# دمج النتائج في DataFrame
result_df = pd.DataFrame({
    'Count': total_counts,
    'Percentage (%)': total_percent.round(1)
})

result_df['Percentage (%)'] = result_df['Percentage (%)'].astype(str) + '%'

# طباعة النتيجة
print(result_df)

              Count Percentage (%)
Total Trades
5               192          14.7%
6               176          13.5%
7               171          13.1%
4               169          13.0%
8               131          10.0%
3               125           9.6%
9                99           7.6%
2                77           5.9%
10               64           4.9%
1                30           2.3%
0                27           2.1%
11               25           1.9%
12                9           0.7%
13                7           0.5%
14                3           0.2%

In [13]:
daily_trades = df_merged

# حساب التكرارات والنسب المئوية
winning_counts = daily_trades['Winning Trades'].value_counts()
winning_percent = daily_trades['Winning Trades'].value_counts(normalize=True) * 100

# دمج النتائج في DataFrame
result_df = pd.DataFrame({
    'Count': winning_counts,
    'Percentage (%)': winning_percent.round(1)
})

result_df['Percentage (%)'] = result_df['Percentage (%)'].astype(str) + '%'

# طباعة النتيجة
print(result_df)

                Count Percentage (%)
Winning Trades
5                 227          17.4%
4                 217          16.6%
3                 186          14.3%
6                 168          12.9%
2                 131          10.0%
7                 126           9.7%
8                  80           6.1%
1                  62           4.8%
0                  45           3.4%
9                  32           2.5%
11                 14           1.1%
10                 14           1.1%
12                  2           0.2%
13                  1           0.1%

In [14]:
daily_trades = df_merged

# حساب التكرارات والنسب المئوية
losing_counts = daily_trades['Losing Trades'].value_counts().sort_index()
losing_percent = daily_trades['Losing Trades'].value_counts(normalize=True).sort_index() * 100

# دمج النتائج في DataFrame
result_df = pd.DataFrame({
    'Count': losing_counts,
    'Percentage (%)': losing_percent.round(1)
})

result_df['Percentage (%)'] = result_df['Percentage (%)'].astype(str) + '%'

# طباعة النتيجة
print(result_df)

               Count Percentage (%)
Losing Trades
0                414          31.7%
1                461          35.3%
2                284          21.8%
3                113           8.7%
4                 26           2.0%
5                  5           0.4%
6                  2           0.2%