In [3]:
import pandas as pd

# المسار الخاص بالملف
file_path = r"C:\Users\Access\Downloads\nor\train\train.csv"

# قراءة البيانات من الملف
df = pd.read_csv(file_path)

In [5]:
df

,Time,Open,High,Low,Close,Volume,EMA_10,EMA_20,RSI_10,ATR_10,Target_Price,Signal
0,03.08.2021 00:00:00.179,0.857201,0.857143,0.856793,0.856793,0.090748,NaN,NaN,NaN,NaN,NaN,0
1,03.08.2021 00:00:00.704,0.857201,0.857551,0.857609,0.857609,0.053222,NaN,NaN,NaN,NaN,NaN,0
2,03.08.2021 00:00:03.581,0.858017,0.858776,0.858425,0.859241,0.068917,NaN,NaN,NaN,NaN,NaN,0
3,03.08.2021 00:00:05.006,0.858425,0.859184,0.858833,0.859649,0.054284,NaN,NaN,NaN,NaN,NaN,0
4,03.08.2021 00:00:11.714,0.859241,0.859184,0.858833,0.858833,0.137951,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
340289,06.09.2021 23:58:44.989,0.856793,0.856735,0.855977,0.855977,0.042365,0.857822,0.857365,0.500293,0.059947,NaN,0
340290,06.09.2021 23:58:52.835,0.855161,0.855102,0.854753,0.854753,0.081072,0.857463,0.857260,0.396903,0.064466,NaN,0
340291,06.09.2021 23:58:54.129,0.854345,0.855102,0.854753,0.855569,0.052514,0.857318,0.857243,0.476291,0.064783,NaN,0
340292,06.09.2021 23:58:58.415,0.854753,0.855102,0.855161,0.855569,0.056880,0.857199,0.857228,0.476291,0.061318,NaN,0
340293,06.09.2021 23:59:13.928,0.854753,0.854694,0.854345,0.854345,0.088388,0.856878,0.857098,0.381124,0.065700,NaN,0

In [6]:
# Assuming df is your DataFrame and 'target' is the name of the target column
train_size = int(0.7 * len(df))  # 70% for training
train_data = df[:train_size]     # First 70% for training
test_data = df[train_size:]      # Remaining 30% for testing

# Split into features (X) and targets (y)
X_train = train_data.drop(columns=['Target_Price', 'Signal'])  # Training features
y_train = train_data[['Target_Price', 'Signal']]                 # Training targets

X_test = test_data.drop(columns=['Target_Price', 'Signal'])    # Testing features
y_test = test_data[['Target_Price', 'Signal']]                   # Testing targets

# Output the size of the splits
print(f"Training set size: {len(X_train)}, Testing set size: {len(X_test)}")

Training set size: 238205, Testing set size: 102089

In [11]:
X_train.shape

(238205, 10)

In [12]:
X_test.shape

(102089, 10)

In [13]:
y_train.shape

(238205, 2)

In [14]:
y_test.shape

(102089, 2)

In [19]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

# المدخلات
input_layer = Input(shape=(X_train.shape[1],))

# الطبقات المخفية
x = Dense(64, activation='relu')(input_layer)
x = Dense(32, activation='relu')(x)

# مخرج لتصنيف الصفقة (شراء/بيع)
trade_signal_output = Dense(1, activation='sigmoid', name='trade_signal')(x)

# مخرج لتوقع هدف السعر (قيمة مستمرة)
target_price_output = Dense(1, activation='linear', name='target_price')(x)

# إنشاء النموذج
model = Model(inputs=input_layer, outputs=[trade_signal_output, target_price_output])

# تهيئة النموذج باستخدام خسارتين مختلفتين لكل مخرج
model.compile(optimizer='adam',
              loss={'trade_signal': 'binary_crossentropy', 'target_price': 'mse'},
              metrics={'trade_signal': 'accuracy', 'target_price': 'mae'})

# تدريب النموذج
model.fit(X_train, {'trade_signal': y_train['Signal'], 'target_price': y_train['Target_Price']}, 
          epochs=10, batch_size=32)

# تقييم النموذج
model.evaluate(X_test, {'trade_signal': y_test['Signal'], 'target_price': y_test['Target_Price']})

ValueError: could not convert string to float: '03.08.2021 00:00:00.179'

In [16]:


# تحويل عمود التاريخ إلى طابع زمني
df['Time'] = pd.to_datetime(df['Time'])

# استخراج مكونات التاريخ (السنة، الشهر، اليوم) كمميزات جديدة
df['year'] = df['Time'].dt.year
df['month'] = df['Time'].dt.month
df['day'] = df['Time'].dt.day
df['hour'] = df['Time'].dt.hour
df['minute'] = df['Time'].dt.minute
df['second'] = df['Time'].dt.second

# ثم يمكنك إزالة عمود التاريخ الأصلي
df = df.drop(columns=['Time'])

ValueError: time data "13.08.2021 00:00:00.237" doesn't match format "%m.%d.%Y %H:%M:%S.%f", at position 113966. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [17]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler


# تحويل عمود 'Time' إلى طابع زمني كامل (بما في ذلك التاريخ والوقت)
df['Time'] = pd.to_datetime(df['Time'], format='%d.%m.%Y %H:%M:%S.%f')

# حساب الفرق الزمني من أول قيمة
df['seconds_since_start'] = (df['Time'] - df['Time'].min()).dt.total_seconds()

# تطبيق النورمليزيشن
scaler = MinMaxScaler()
df['normalized_time'] = scaler.fit_transform(df[['seconds_since_start']])

print(df)

                          Time      Open      High       Low     Close  \
0      2021-08-03 00:00:00.179  0.857201  0.857143  0.856793  0.856793
1      2021-08-03 00:00:00.704  0.857201  0.857551  0.857609  0.857609
2      2021-08-03 00:00:03.581  0.858017  0.858776  0.858425  0.859241
3      2021-08-03 00:00:05.006  0.858425  0.859184  0.858833  0.859649
4      2021-08-03 00:00:11.714  0.859241  0.859184  0.858833  0.858833
...                        ...       ...       ...       ...       ...
340289 2021-09-06 23:58:44.989  0.856793  0.856735  0.855977  0.855977
340290 2021-09-06 23:58:52.835  0.855161  0.855102  0.854753  0.854753
340291 2021-09-06 23:58:54.129  0.854345  0.855102  0.854753  0.855569
340292 2021-09-06 23:58:58.415  0.854753  0.855102  0.855161  0.855569
340293 2021-09-06 23:59:13.928  0.854753  0.854694  0.854345  0.854345

          Volume    EMA_10    EMA_20    RSI_10    ATR_10  Target_Price  \
0       0.090748       NaN       NaN       NaN       NaN           NaN
1       0.053222       NaN       NaN       NaN       NaN           NaN
2       0.068917       NaN       NaN       NaN       NaN           NaN
3       0.054284       NaN       NaN       NaN       NaN           NaN
4       0.137951       NaN       NaN       NaN       NaN           NaN
...          ...       ...       ...       ...       ...           ...
340289  0.042365  0.857822  0.857365  0.500293  0.059947           NaN
340290  0.081072  0.857463  0.857260  0.396903  0.064466           NaN
340291  0.052514  0.857318  0.857243  0.476291  0.064783           NaN
340292  0.056880  0.857199  0.857228  0.476291  0.061318           NaN
340293  0.088388  0.856878  0.857098  0.381124  0.065700           NaN

        Signal  seconds_since_start  normalized_time
0            0                0.000     0.000000e+00
1            0                0.525     1.736138e-07
2            0                3.402     1.125017e-06
3            0                4.827     1.596255e-06
4            0               11.535     3.814542e-06
...        ...                  ...              ...
340289       0          3023924.810     9.999904e-01
340290       0          3023932.656     9.999930e-01
340291       0          3023933.950     9.999935e-01
340292       0          3023938.236     9.999949e-01
340293       0          3023953.749     1.000000e+00

[340294 rows x 14 columns]

In [18]:
df

,Time,Open,High,Low,Close,Volume,EMA_10,EMA_20,RSI_10,ATR_10,Target_Price,Signal,seconds_since_start,normalized_time
0,2021-08-03 00:00:00.179,0.857201,0.857143,0.856793,0.856793,0.090748,NaN,NaN,NaN,NaN,NaN,0,0.000,0.000000e+00
1,2021-08-03 00:00:00.704,0.857201,0.857551,0.857609,0.857609,0.053222,NaN,NaN,NaN,NaN,NaN,0,0.525,1.736138e-07
2,2021-08-03 00:00:03.581,0.858017,0.858776,0.858425,0.859241,0.068917,NaN,NaN,NaN,NaN,NaN,0,3.402,1.125017e-06
3,2021-08-03 00:00:05.006,0.858425,0.859184,0.858833,0.859649,0.054284,NaN,NaN,NaN,NaN,NaN,0,4.827,1.596255e-06
4,2021-08-03 00:00:11.714,0.859241,0.859184,0.858833,0.858833,0.137951,NaN,NaN,NaN,NaN,NaN,0,11.535,3.814542e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340289,2021-09-06 23:58:44.989,0.856793,0.856735,0.855977,0.855977,0.042365,0.857822,0.857365,0.500293,0.059947,NaN,0,3023924.810,9.999904e-01
340290,2021-09-06 23:58:52.835,0.855161,0.855102,0.854753,0.854753,0.081072,0.857463,0.857260,0.396903,0.064466,NaN,0,3023932.656,9.999930e-01
340291,2021-09-06 23:58:54.129,0.854345,0.855102,0.854753,0.855569,0.052514,0.857318,0.857243,0.476291,0.064783,NaN,0,3023933.950,9.999935e-01
340292,2021-09-06 23:58:58.415,0.854753,0.855102,0.855161,0.855569,0.056880,0.857199,0.857228,0.476291,0.061318,NaN,0,3023938.236,9.999949e-01
340293,2021-09-06 23:59:13.928,0.854753,0.854694,0.854345,0.854345,0.088388,0.856878,0.857098,0.381124,0.065700,NaN,0,3023953.749,1.000000e+00