In [1]:
import pandas as pd
df= pd.read_csv(r"C:\Users\Access\Documents\AI ROBOT\XAUUSD_Candlestick_1_M_BID_2020-1-1_2024-12-31.csv")

In [2]:
df=df.drop(columns='Volume')

In [3]:
import pandas as pd

# تحويل العمود الزمني إلى نوع datetime وتعيينه كمؤشر
df['Gmt time'] = pd.to_datetime(df['Gmt time'])
df.set_index('Gmt time', inplace=True)

# تحويل البيانات من 1 دقيقة إلى 5 دقائق
df_5m = df.resample('5T').agg({
    'Open': 'first',   # أول سعر افتتاح في الفاصل الزمني
    'High': 'max',     # أعلى سعر في الفاصل الزمني
    'Low': 'min',      # أقل سعر في الفاصل الزمني
    'Close': 'last'    # آخر سعر إغلاق في الفاصل الزمني
})

# عرض النتيجة
print(df_5m)

C:\Users\Access\AppData\Local\Temp\ipykernel_51148\422809626.py:8: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  df_5m = df.resample('5T').agg({

                         Open      High       Low     Close
Gmt time
2020-01-01 00:00:00  1516.915  1516.915  1516.915  1516.915
2020-01-01 00:05:00  1516.915  1516.915  1516.915  1516.915
2020-01-01 00:10:00  1516.915  1516.915  1516.915  1516.915
2020-01-01 00:15:00  1516.915  1516.915  1516.915  1516.915
2020-01-01 00:20:00  1516.915  1516.915  1516.915  1516.915
...                       ...       ...       ...       ...
2024-12-31 23:35:00  2624.255  2624.255  2624.255  2624.255
2024-12-31 23:40:00  2624.255  2624.255  2624.255  2624.255
2024-12-31 23:45:00  2624.255  2624.255  2624.255  2624.255
2024-12-31 23:50:00  2624.255  2624.255  2624.255  2624.255
2024-12-31 23:55:00  2624.255  2624.255  2624.255  2624.255

[526176 rows x 4 columns]

In [4]:
df_5m=df_5m.reset_index(drop=False)

In [5]:
import pandas as pd

df = df_5m.copy()

# تعريف دالة التحقق من الشمعة الكبيرة (تبقى كما هي)
def is_large_body(candle):
    body = abs(candle['Open'] - candle['Close'])
    lower_shadow = abs(candle['Low'] - min(candle['Open'], candle['Close']))
    upper_shadow = abs(candle['High'] - max(candle['Open'], candle['Close']))
    return (body * 2) > (lower_shadow + upper_shadow)

# تعديل دالة الهامر لتصبح شمعة Shooting Star (مقلوبة)
def is_shooting_star(candle):
    body = abs(candle['Open'] - candle['Close'])
    upper_shadow = abs(candle['High'] - max(candle['Open'], candle['Close']))
    lower_shadow = abs(candle['Low'] - min(candle['Open'], candle['Close']))
    return upper_shadow > 0.1 * body and lower_shadow < body

# تعديل دالة الصفقة لصفقات البيع
def calculate_sell_trade_shooting_star(row, df, tp_multiplier=1.5, sl_multiplier=0.5):
    idx = row.name
    if idx == df.index[0]:
        return 0, None, None
    
    first_candle = df.loc[df.index[df.index.get_loc(idx) - 1]]
    second_candle = row
    
    # الشرط المعكوس: شمعة صاعدة كبيرة تليها شمعة Shooting Star
    if is_large_body(first_candle) and first_candle['Open'] < first_candle['Close'] and is_shooting_star(second_candle) and second_candle['Open'] > second_candle['Close']:
        points = abs(first_candle['Open'] - first_candle['Close'])
        #take_profit = second_candle['Close'] - (points * tp_multiplier)
        stop_loss = second_candle['Close'] + (points * sl_multiplier)
        take_profit =  second_candle['Close'] - (tp_multiplier*abs(stop_loss - second_candle['Close']))

        return 1, take_profit, stop_loss
    
    return 0, None, None

# تطبيق الأعمدة الجديدة للصفقات البيعية
df['sell_trade_shooting'], df['tp_sell_shooting'], df['sl_sell_shooting'] = zip(*df.apply(
    lambda row: calculate_sell_trade_shooting_star(row, df), axis=1))

# تحديد نوع الصفقة للبيع
df['trade_type_shooting'] = df.apply(lambda row: -1 if row['sell_trade_shooting'] == 1 else 0, axis=1)

# دمج أعمدة TP و SL
df['tp_shooting'] = df.apply(lambda row: row['tp_sell_shooting'] if row['trade_type_shooting'] == -1 else None, axis=1)
df['sl_shooting'] = df.apply(lambda row: row['sl_sell_shooting'] if row['trade_type_shooting'] == -1 else None, axis=1)


# تعديل دالة تحديد نتيجة الصفقة للبيع
def determine_trade_result_shooting(row, df):
    idx = row.name
    if row['trade_type_shooting'] == -1:  # صفقة بيع
        for i in range(df.index.get_loc(idx) + 1, len(df)):
            future_row = df.iloc[i]
            if future_row['Low'] <= row['tp_shooting']:
                return 2  # رابحة
            elif future_row['High'] >= row['sl_shooting']:
                return 1  # خاسرة
    return 0  # لا توجد نتيجة


# تطبيق دالة النتائج
df['trade_result_shooting'] = df.apply(lambda row: determine_trade_result_shooting(row, df), axis=1)

# عرض النتائج
print(df[['Gmt time','Open', 'High', 'Low', 'Close', 'trade_type_shooting', 'trade_result_shooting', 'tp_shooting', 'sl_shooting']])

                  Gmt time      Open      High       Low     Close  \
0      2020-01-01 00:00:00  1516.915  1516.915  1516.915  1516.915
1      2020-01-01 00:05:00  1516.915  1516.915  1516.915  1516.915
2      2020-01-01 00:10:00  1516.915  1516.915  1516.915  1516.915
3      2020-01-01 00:15:00  1516.915  1516.915  1516.915  1516.915
4      2020-01-01 00:20:00  1516.915  1516.915  1516.915  1516.915
...                    ...       ...       ...       ...       ...
526171 2024-12-31 23:35:00  2624.255  2624.255  2624.255  2624.255
526172 2024-12-31 23:40:00  2624.255  2624.255  2624.255  2624.255
526173 2024-12-31 23:45:00  2624.255  2624.255  2624.255  2624.255
526174 2024-12-31 23:50:00  2624.255  2624.255  2624.255  2624.255
526175 2024-12-31 23:55:00  2624.255  2624.255  2624.255  2624.255

        trade_type_shooting  trade_result_shooting  tp_shooting  sl_shooting
0                         0                      0          NaN          NaN
1                         0                      0          NaN          NaN
2                         0                      0          NaN          NaN
3                         0                      0          NaN          NaN
4                         0                      0          NaN          NaN
...                     ...                    ...          ...          ...
526171                    0                      0          NaN          NaN
526172                    0                      0          NaN          NaN
526173                    0                      0          NaN          NaN
526174                    0                      0          NaN          NaN
526175                    0                      0          NaN          NaN

[526176 rows x 9 columns]

In [6]:
df = df[df['trade_type_shooting'] != 0]

In [7]:
df = df[['Gmt time','Open', 'High', 'Low', 'Close', 'trade_type_shooting', 'trade_result_shooting', 'tp_shooting', 'sl_shooting']]

In [8]:
df

,Gmt time,Open,High,Low,Close,trade_type_shooting,trade_result_shooting,tp_shooting,sl_shooting
330,2020-01-02 03:30:00,1520.295,1520.435,1520.185,1520.215,-1,1,1520.08000,1520.3050
334,2020-01-02 03:50:00,1520.355,1520.435,1520.165,1520.165,-1,1,1519.91225,1520.3335
361,2020-01-02 06:05:00,1520.505,1520.768,1520.345,1520.405,-1,1,1520.12750,1520.5900
372,2020-01-02 07:00:00,1520.945,1521.375,1520.435,1520.575,-1,2,1520.30500,1520.7550
375,2020-01-02 07:15:00,1520.415,1520.525,1519.825,1519.875,-1,2,1519.65000,1520.0250
...,...,...,...,...,...,...,...,...,...
526083,2024-12-31 16:15:00,2624.915,2625.198,2623.164,2623.164,-1,1,2621.72175,2624.1255
526091,2024-12-31 16:55:00,2625.495,2625.835,2624.864,2625.165,-1,2,2624.70675,2625.4705
526103,2024-12-31 17:55:00,2624.835,2625.265,2623.955,2624.155,-1,2,2623.57000,2624.5450
526130,2024-12-31 20:10:00,2624.404,2624.524,2622.948,2623.248,-1,2,2622.96300,2623.4380
526149,2024-12-31 21:45:00,2624.395,2624.675,2623.908,2624.008,-1,2,2623.86550,2624.1030

In [9]:


result = df['trade_result_shooting'].value_counts().sort_index()
percent = df['trade_result_shooting'].value_counts(normalize=True).sort_index() * 100

# دمج النتائج في DataFrame
result_df = pd.DataFrame({
    'Count': result,
    'Percentage (%)': percent.round(1)})

result_df['Percentage (%)'] = result_df['Percentage (%)'].astype(str) + '%'

print(result_df)

                       Count Percentage (%)
trade_result_shooting
1                      13304          49.7%
2                      13456          50.3%

In [10]:
import pandas as pd

# تصفية الصفقات التي تحتوي على نتائج
df = df[df['trade_result_shooting'] != 0]

# استخراج التاريخ فقط
df['Gmt date'] = df['Gmt time'].dt.date

# تصنيف الصفقات
df['trade_type'] = df['trade_result_shooting'].apply(lambda x: 'رابحة' if x == 2 else 'خاسرة')

# حساب عدد الصفقات لكل يوم
daily_trades = df.groupby(['Gmt date', 'trade_type']).size().unstack(fill_value=0)

# إعادة تسمية الأعمدة
daily_trades = daily_trades.rename(columns={'رابحة': 'Winning Trades', 'خاسرة': 'Losing Trades'})

# إنشاء نطاق تواريخ شامل من البيانات الأصلية
start_date = df['Gmt time'].min().normalize()
end_date = df['Gmt time'].max().normalize()
all_dates = pd.date_range(start=start_date, end=end_date, freq='D')

# تحويل الفهرس إلى تنسيق تاريخي
daily_trades.index = pd.to_datetime(daily_trades.index)

# إعادة الفهرس ليشمل جميع التواريخ
daily_trades = daily_trades.reindex(all_dates, fill_value=0)

# تصفية أيام السبت (5) والأحد (6) باستخدام weekday
daily_trades = daily_trades[daily_trades.index.weekday < 5]  # 0-4 = من الاثنين إلى الجمعة

# إضافة عمود الصفقات الكلية
daily_trades['Total Trades'] = daily_trades['Winning Trades'] + daily_trades['Losing Trades']

# إعادة تنسيق الفهرس لعرضه كتواريخ بدون وقت
daily_trades.index = daily_trades.index.date

print(daily_trades)

trade_type  Losing Trades  Winning Trades  Total Trades
2020-01-02              8               6            14
2020-01-03              9               9            18
2020-01-06             14               8            22
2020-01-07             12              12            24
2020-01-08             11               7            18
...                   ...             ...           ...
2024-12-25              0               1             1
2024-12-26              6               7            13
2024-12-27             10              17            27
2024-12-30              8               7            15
2024-12-31              9              11            20

[1304 rows x 3 columns]

In [11]:
daily_trades.describe().round(1).drop(['count','std'])

trade_type  Losing Trades  Winning Trades  Total Trades
mean                 10.1            10.2          20.3
min                   0.0             0.0           0.0
25%                   7.0             8.0          17.0
50%                  10.0            10.0          21.0
75%                  13.0            13.0          24.0
max                  23.0            23.0          37.0