In [2]:
from polygon.rest.client import RESTClient

client = RESTClient("f1j6d2fq4L9pgzUJaXhEQ6Qm21XLr0Qj")

aggs = []
for a in client.list_aggs(
    "AAPL",
    1,
    "minute",
    "2024-06-01",
    "2025-06-01"
    #limit=50000,
):
    aggs.append(a)

print(aggs)

ModuleNotFoundError: No module named 'polygon.rest'

In [3]:
pip uninstall polygon -y

Found existing installation: polygon 1.2.6
Uninstalling polygon-1.2.6:
  Successfully uninstalled polygon-1.2.6
Note: you may need to restart the kernel to use updated packages.

In [1]:
pip install polygon-api-client

Defaulting to user installation because normal site-packages is not writeable
Collecting polygon-api-client
  Downloading polygon_api_client-1.15.3-py3-none-any.whl.metadata (952 bytes)
Requirement already satisfied: certifi<2026.0.0,>=2022.5.18 in c:\programdata\anaconda3\lib\site-packages (from polygon-api-client) (2025.4.26)
Requirement already satisfied: urllib3<3.0.0,>=1.26.9 in c:\users\access\appdata\roaming\python\python312\site-packages (from polygon-api-client) (2.4.0)
Requirement already satisfied: websockets<15.0,>=10.3 in c:\users\access\appdata\roaming\python\python312\site-packages (from polygon-api-client) (10.4)
Downloading polygon_api_client-1.15.3-py3-none-any.whl (54 kB)
Installing collected packages: polygon-api-client
Successfully installed polygon-api-client-1.15.3
Note: you may need to restart the kernel to use updated packages.

In [7]:
from polygon  import RESTClient

client = RESTClient("f1j6d2fq4L9pgzUJaXhEQ6Qm21XLr0Qj")

aggs = []
for a in client.list_aggs(
    "AAPL",
    5,
    "minute",
    "2020-06-01",
    "2025-06-01",
    limit=50000,
):
    aggs.append(a)

print(aggs)

MaxRetryError: HTTPSConnectionPool(host='api.polygon.io', port=443): Max retries exceeded with url: /v2/aggs/ticker/AAPL/range/1/minute/1733323020000/2025-06-01?cursor=bGltaXQ9NTAwMDAmc29ydD1hc2M (Caused by ResponseError('too many 429 error responses'))

In [17]:
from polygon import RESTClient
import pandas as pd

# الاتصال بـ Polygon API
client = RESTClient("f1j6d2fq4L9pgzUJaXhEQ6Qm21XLr0Qj")

# تخزين النتائج
aggs = []

# استدعاء بيانات الشموع
for a in client.list_aggs(
    "AAPL",
    5,                     # 5 دقائق
    "minute",
    "2022-01-01",          # سنة واحدة فقط مثالاً
    "2022-12-31",
    limit=50000,
):
    aggs.append(a)

# تحويل النتائج إلى DataFrame
df22 = pd.DataFrame([{
    'timestamp': pd.to_datetime(a.timestamp, unit='ms'),
    'open': a.open,
    'high': a.high,
    'low': a.low,
    'close': a.close,
    'volume': a.volume,
    'vwap': a.vwap,
    'transactions': a.transactions
} for a in aggs])

# عرض أول 5 صفوف
print(df22.head())

BadResponse: {"status":"NOT_AUTHORIZED","request_id":"4d016960dffe59f2d32890f26c17c054","message":"Your plan doesn't include this data timeframe. Please upgrade your plan at https://polygon.io/pricing"}

In [10]:
df24 = df

In [12]:
df25

,timestamp,open,high,low,close,volume,vwap,transactions
0,2025-01-02 09:00:00,251.3600,251.42,250.6000,251.1300,5181.0,251.2158,333
1,2025-01-02 09:05:00,251.1500,251.45,251.1500,251.3900,5247.0,251.3060,138
2,2025-01-02 09:10:00,251.5400,251.54,251.4200,251.4200,1331.0,251.4770,62
3,2025-01-02 09:15:00,251.4100,251.70,251.3900,251.6600,6557.0,251.6117,194
4,2025-01-02 09:20:00,251.6600,251.90,251.6600,251.9000,4873.0,251.8040,107
...,...,...,...,...,...,...,...,...
27529,2025-08-05 23:35:00,202.7889,202.80,202.7001,202.7071,971.0,202.7364,20
27530,2025-08-05 23:40:00,202.7200,202.79,202.7088,202.7088,676.0,202.7459,28
27531,2025-08-05 23:45:00,202.7900,202.86,202.7200,202.7300,2508.0,202.7997,86
27532,2025-08-05 23:50:00,202.7300,202.80,202.7300,202.7999,2763.0,202.7801,37
27533,2025-08-05 23:55:00,202.7980,202.80,202.7700,202.8000,4348.0,202.7820,84

In [14]:
df23

,timestamp,open,high,low,close,volume,vwap,transactions
0,2023-08-07 08:00:00,183.0400,183.49,182.5400,183.3500,22483.0,183.2682,518
1,2023-08-07 08:05:00,183.2500,183.35,183.0000,183.0100,16645.0,183.1792,357
2,2023-08-07 08:10:00,182.8900,183.00,182.7500,182.9300,16279.0,182.8757,338
3,2023-08-07 08:15:00,182.9500,182.97,182.9000,182.9700,3718.0,182.9432,133
4,2023-08-07 08:20:00,183.0000,183.00,182.9800,183.0000,4919.0,182.9977,175
...,...,...,...,...,...,...,...,...
18643,2023-12-30 00:35:00,192.1400,192.14,192.1100,192.1200,1639.0,192.1304,44
18644,2023-12-30 00:40:00,192.1118,192.15,192.1118,192.1500,2863.0,192.1357,41
18645,2023-12-30 00:45:00,192.1500,192.22,192.1500,192.2000,3105.0,192.2042,37
18646,2023-12-30 00:50:00,192.1600,192.24,192.1600,192.2200,8060.0,192.2218,54
18647,2023-12-30 00:55:00,192.2400,192.24,192.1000,192.1501,6212.0,192.1833,89

In [15]:
df = pd.concat([df23,df24,df25])

In [16]:
df

,timestamp,open,high,low,close,volume,vwap,transactions
0,2023-08-07 08:00:00,183.0400,183.49,182.5400,183.3500,22483.0,183.2682,518
1,2023-08-07 08:05:00,183.2500,183.35,183.0000,183.0100,16645.0,183.1792,357
2,2023-08-07 08:10:00,182.8900,183.00,182.7500,182.9300,16279.0,182.8757,338
3,2023-08-07 08:15:00,182.9500,182.97,182.9000,182.9700,3718.0,182.9432,133
4,2023-08-07 08:20:00,183.0000,183.00,182.9800,183.0000,4919.0,182.9977,175
...,...,...,...,...,...,...,...,...
27529,2025-08-05 23:35:00,202.7889,202.80,202.7001,202.7071,971.0,202.7364,20
27530,2025-08-05 23:40:00,202.7200,202.79,202.7088,202.7088,676.0,202.7459,28
27531,2025-08-05 23:45:00,202.7900,202.86,202.7200,202.7300,2508.0,202.7997,86
27532,2025-08-05 23:50:00,202.7300,202.80,202.7300,202.7999,2763.0,202.7801,37
27533,2025-08-05 23:55:00,202.7980,202.80,202.7700,202.8000,4348.0,202.7820,84

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 92477 entries, 0 to 27533
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     92477 non-null  datetime64[ns]
 1   open          92477 non-null  float64
 2   high          92477 non-null  float64
 3   low           92477 non-null  float64
 4   close         92477 non-null  float64
 5   volume        92477 non-null  float64
 6   vwap          92477 non-null  float64
 7   transactions  92477 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(1)
memory usage: 6.3 MB

In [19]:
df.to_csv(r"C:\Users\Access\Documents\DATA\AAPL\df-23-8-25-8.csv" , index=False)

In [21]:
df['vol/trans'] = df['volume']/df['transactions']

In [25]:
df.columns

Index(['timestamp', 'open', 'high', 'low', 'close', 'volume', 'vwap',
       'transactions', 'vol/trans'],
      dtype='object')

In [26]:
import pandas as pd
import numpy as np

# Relative Volume (RVOL)
df['RVOL'] = df['volume'] / df['volume'].rolling(window=20).mean()

# Volume Rate of Change (VROC)
df['VROC'] = (df['volume'] - df['volume'].shift(5)) / df['volume'].shift(5)

# Cumulative Delta Volume (لو عندك بيانات ask_volume و bid_volume)
# df['cum_delta_vol'] = (df['ask_volume'] - df['bid_volume']).cumsum()

In [27]:
df

,timestamp,open,high,low,close,volume,vwap,transactions,vol/trans,RVOL,VROC
0,2023-08-07 08:00:00,183.0400,183.49,182.5400,183.3500,22483.0,183.2682,518,43.403475,NaN,NaN
1,2023-08-07 08:05:00,183.2500,183.35,183.0000,183.0100,16645.0,183.1792,357,46.624650,NaN,NaN
2,2023-08-07 08:10:00,182.8900,183.00,182.7500,182.9300,16279.0,182.8757,338,48.162722,NaN,NaN
3,2023-08-07 08:15:00,182.9500,182.97,182.9000,182.9700,3718.0,182.9432,133,27.954887,NaN,NaN
4,2023-08-07 08:20:00,183.0000,183.00,182.9800,183.0000,4919.0,182.9977,175,28.108571,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
27529,2025-08-05 23:35:00,202.7889,202.80,202.7001,202.7071,971.0,202.7364,20,48.550000,0.397837,-0.734917
27530,2025-08-05 23:40:00,202.7200,202.79,202.7088,202.7088,676.0,202.7459,28,24.142857,0.283171,-0.834110
27531,2025-08-05 23:45:00,202.7900,202.86,202.7200,202.7300,2508.0,202.7997,86,29.162791,1.142493,0.366757
27532,2025-08-05 23:50:00,202.7300,202.80,202.7300,202.7999,2763.0,202.7801,37,74.675676,1.329004,0.965149
27533,2025-08-05 23:55:00,202.7980,202.80,202.7700,202.8000,4348.0,202.7820,84,51.761905,1.963246,1.184925

In [28]:
# Volume Weighted Spread
df['spread_vol'] = (df['high'] - df['low']) * df['RVOL']

# VWAP Deviation (بالانحراف المعياري)
vwap_std = df['vwap'].rolling(window=20).std()
df['vwap_dev'] = (df['close'] - df['vwap']) / vwap_std

# Volume per Transaction
df['vol_per_tx'] = df['volume'] / df['transactions']

In [29]:
df

,timestamp,open,high,low,close,volume,vwap,transactions,vol/trans,RVOL,VROC,spread_vol,vwap_dev,vol_per_tx
0,2023-08-07 08:00:00,183.0400,183.49,182.5400,183.3500,22483.0,183.2682,518,43.403475,NaN,NaN,NaN,NaN,43.403475
1,2023-08-07 08:05:00,183.2500,183.35,183.0000,183.0100,16645.0,183.1792,357,46.624650,NaN,NaN,NaN,NaN,46.624650
2,2023-08-07 08:10:00,182.8900,183.00,182.7500,182.9300,16279.0,182.8757,338,48.162722,NaN,NaN,NaN,NaN,48.162722
3,2023-08-07 08:15:00,182.9500,182.97,182.9000,182.9700,3718.0,182.9432,133,27.954887,NaN,NaN,NaN,NaN,27.954887
4,2023-08-07 08:20:00,183.0000,183.00,182.9800,183.0000,4919.0,182.9977,175,28.108571,NaN,NaN,NaN,NaN,28.108571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27529,2025-08-05 23:35:00,202.7889,202.80,202.7001,202.7071,971.0,202.7364,20,48.550000,0.397837,-0.734917,0.039744,-0.668654,48.550000
27530,2025-08-05 23:40:00,202.7200,202.79,202.7088,202.7088,676.0,202.7459,28,24.142857,0.283171,-0.834110,0.022993,-0.896235,24.142857
27531,2025-08-05 23:45:00,202.7900,202.86,202.7200,202.7300,2508.0,202.7997,86,29.162791,1.142493,0.366757,0.159949,-1.636646,29.162791
27532,2025-08-05 23:50:00,202.7300,202.80,202.7300,202.7999,2763.0,202.7801,37,74.675676,1.329004,0.965149,0.093030,0.557225,74.675676
27533,2025-08-05 23:55:00,202.7980,202.80,202.7700,202.8000,4348.0,202.7820,84,51.761905,1.963246,1.184925,0.058897,0.602781,51.761905

In [30]:
# Volume Pressure Index (لو عندك بيانات اتجاه الصفقات)
green_vol = df.loc[df['close'] > df['open'], 'volume']
red_vol   = df.loc[df['close'] < df['open'], 'volume']
df['VPI'] = (green_vol.sum() - red_vol.sum()) / (green_vol.sum() + red_vol.sum())

# Accumulation/Distribution based on VWAP
df['accum_dist_vwap'] = np.where(df['close'] > df['vwap'], df['volume'], -df['volume'])
df['accum_dist_vwap'] = df['accum_dist_vwap'].cumsum()

In [31]:
df

,timestamp,open,high,low,close,volume,vwap,transactions,vol/trans,RVOL,VROC,spread_vol,vwap_dev,vol_per_tx,VPI,accum_dist_vwap
0,2023-08-07 08:00:00,183.0400,183.49,182.5400,183.3500,22483.0,183.2682,518,43.403475,NaN,NaN,NaN,NaN,43.403475,0.024176,22483.0
1,2023-08-07 08:05:00,183.2500,183.35,183.0000,183.0100,16645.0,183.1792,357,46.624650,NaN,NaN,NaN,NaN,46.624650,0.024176,5838.0
2,2023-08-07 08:10:00,182.8900,183.00,182.7500,182.9300,16279.0,182.8757,338,48.162722,NaN,NaN,NaN,NaN,48.162722,0.024176,22117.0
3,2023-08-07 08:15:00,182.9500,182.97,182.9000,182.9700,3718.0,182.9432,133,27.954887,NaN,NaN,NaN,NaN,27.954887,0.024176,25835.0
4,2023-08-07 08:20:00,183.0000,183.00,182.9800,183.0000,4919.0,182.9977,175,28.108571,NaN,NaN,NaN,NaN,28.108571,0.024176,30754.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27529,2025-08-05 23:35:00,202.7889,202.80,202.7001,202.7071,971.0,202.7364,20,48.550000,0.397837,-0.734917,0.039744,-0.668654,48.550000,0.024176,393695512.0
27530,2025-08-05 23:40:00,202.7200,202.79,202.7088,202.7088,676.0,202.7459,28,24.142857,0.283171,-0.834110,0.022993,-0.896235,24.142857,0.024176,393694836.0
27531,2025-08-05 23:45:00,202.7900,202.86,202.7200,202.7300,2508.0,202.7997,86,29.162791,1.142493,0.366757,0.159949,-1.636646,29.162791,0.024176,393692328.0
27532,2025-08-05 23:50:00,202.7300,202.80,202.7300,202.7999,2763.0,202.7801,37,74.675676,1.329004,0.965149,0.093030,0.557225,74.675676,0.024176,393695091.0
27533,2025-08-05 23:55:00,202.7980,202.80,202.7700,202.8000,4348.0,202.7820,84,51.761905,1.963246,1.184925,0.058897,0.602781,51.761905,0.024176,393699439.0

In [34]:
# Volume Spike Detector → 1 أو 0
df['vol_spike'] = (df['volume'] > (df['volume'].rolling(window=10).mean() * 2)).astype(int)

# Volume Climax Bar → 1 أو 0
max_vol = df['volume'].rolling(window=20).max()
wide_range = (df['high'] - df['low']) > (df['high'] - df['low']).rolling(window=20).mean()
df['climax_bar'] = ((df['volume'] == max_vol) & wide_range).astype(int)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 92477 entries, 0 to 27533
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   timestamp        92477 non-null  datetime64[ns]
 1   open             92477 non-null  float64
 2   high             92477 non-null  float64
 3   low              92477 non-null  float64
 4   close            92477 non-null  float64
 5   volume           92477 non-null  float64
 6   vwap             92477 non-null  float64
 7   transactions     92477 non-null  int64
 8   vol/trans        92477 non-null  float64
 9   RVOL             92458 non-null  float64
 10  VROC             92472 non-null  float64
 11  spread_vol       92458 non-null  float64
 12  vwap_dev         92458 non-null  float64
 13  vol_per_tx       92477 non-null  float64
 14  VPI              92477 non-null  float64
 15  accum_dist_vwap  92477 non-null  float64
 16  vol_spike        92477 non-null  int32
 17  climax_bar       92477 non-null  int32
dtypes: datetime64[ns](1), float64(14), int32(2), int64(1)
memory usage: 12.7 MB

In [37]:
import pandas as pd
import numpy as np

# Micro Trend Slope (5 شموع)
df['micro_trend_slope'] = (df['close'] - df['close'].shift(5)) / \
                          (df['high'].rolling(5).max() - df['low'].rolling(5).min())

# Price Change per Second (لو عندك بيانات وقت بالثواني)
# تحويل timestamp إلى datetime
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['seconds_diff'] = (df['timestamp'] - df['timestamp'].shift(1)).dt.total_seconds()
df['price_change_per_sec'] = (df['close'] - df['close'].shift(1)) / df['seconds_diff']

In [38]:
# Position in Range (آخر 20 شمعة)
window_range = 20
low_min = df['low'].rolling(window_range).min()
high_max = df['high'].rolling(window_range).max()
df['pos_in_range'] = (df['close'] - low_min) / (high_max - low_min)

# Micro Support/Resistance Distance
df['dist_to_recent_high'] = df['high'].rolling(window_range).max() - df['close']
df['dist_to_recent_low'] = df['close'] - df['low'].rolling(window_range).min()

# Candle Body-to-Range Ratio
df['body_to_range'] = abs(df['close'] - df['open']) / (df['high'] - df['low'])

In [39]:
# Transaction Density
df['tx_density'] = df['transactions'] / df['volume']

# VWAP Pullback Strength
df['vwap_pullback'] = (df['vwap'] - df['close'].shift(1)) / df['vwap']

# Volume Shock + Price Reaction
vol_avg = df['volume'].rolling(20).mean()
df['vol_shock'] = (df['volume'] > (vol_avg * 2)).astype(int)
df['price_reaction_next'] = df['close'].shift(-1) - df['close']

In [40]:
df

,timestamp,open,high,low,close,volume,vwap,transactions,vol/trans,RVOL,...,seconds_diff,price_change_per_sec,pos_in_range,dist_to_recent_high,dist_to_recent_low,body_to_range,tx_density,vwap_pullback,vol_shock,price_reaction_next
0,2023-08-07 08:00:00,183.0400,183.49,182.5400,183.3500,22483.0,183.2682,518,43.403475,NaN,...,NaN,NaN,NaN,NaN,NaN,0.326316,0.023040,NaN,0,-0.3400
1,2023-08-07 08:05:00,183.2500,183.35,183.0000,183.0100,16645.0,183.1792,357,46.624650,NaN,...,300.0,-1.133333e-03,NaN,NaN,NaN,0.685714,0.021448,-0.000932,0,-0.0800
2,2023-08-07 08:10:00,182.8900,183.00,182.7500,182.9300,16279.0,182.8757,338,48.162722,NaN,...,300.0,-2.666667e-04,NaN,NaN,NaN,0.160000,0.020763,-0.000734,0,0.0400
3,2023-08-07 08:15:00,182.9500,182.97,182.9000,182.9700,3718.0,182.9432,133,27.954887,NaN,...,300.0,1.333333e-04,NaN,NaN,NaN,0.285714,0.035772,0.000072,0,0.0300
4,2023-08-07 08:20:00,183.0000,183.00,182.9800,183.0000,4919.0,182.9977,175,28.108571,NaN,...,300.0,1.000000e-04,NaN,NaN,NaN,0.000000,0.035576,0.000151,0,-0.0300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27529,2025-08-05 23:35:00,202.7889,202.80,202.7001,202.7071,971.0,202.7364,20,48.550000,0.397837,...,300.0,2.366667e-05,0.294242,0.2329,0.0971,0.818819,0.020597,0.000180,0,0.0017
27530,2025-08-05 23:40:00,202.7200,202.79,202.7088,202.7088,676.0,202.7459,28,24.142857,0.283171,...,300.0,5.666667e-06,0.299394,0.2312,0.0988,0.137931,0.041420,0.000191,0,0.0212
27531,2025-08-05 23:45:00,202.7900,202.86,202.7200,202.7300,2508.0,202.7997,86,29.162791,1.142493,...,300.0,7.066667e-05,0.480000,0.1300,0.1200,0.428571,0.034290,0.000448,0,0.0699
27532,2025-08-05 23:50:00,202.7300,202.80,202.7300,202.7999,2763.0,202.7801,37,74.675676,1.329004,...,300.0,2.330000e-04,0.738696,0.0601,0.1699,0.998571,0.013391,0.000247,0,0.0001
27533,2025-08-05 23:55:00,202.7980,202.80,202.7700,202.8000,4348.0,202.7820,84,51.761905,1.963246,...,300.0,3.333333e-07,0.739130,0.0600,0.1700,0.066667,0.019319,-0.000088,0,NaN

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 92477 entries, 0 to 27533
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             92477 non-null  datetime64[ns]
 1   open                  92477 non-null  float64
 2   high                  92477 non-null  float64
 3   low                   92477 non-null  float64
 4   close                 92477 non-null  float64
 5   volume                92477 non-null  float64
 6   vwap                  92477 non-null  float64
 7   transactions          92477 non-null  int64
 8   vol/trans             92477 non-null  float64
 9   RVOL                  92458 non-null  float64
 10  VROC                  92472 non-null  float64
 11  spread_vol            92458 non-null  float64
 12  vwap_dev              92458 non-null  float64
 13  vol_per_tx            92477 non-null  float64
 14  VPI                   92477 non-null  float64
 15  accum_dist_vwap       92477 non-null  float64
 16  vol_spike             92477 non-null  int32
 17  climax_bar            92477 non-null  int32
 18  micro_trend_slope     92472 non-null  float64
 19  seconds_diff          92476 non-null  float64
 20  price_change_per_sec  92476 non-null  float64
 21  pos_in_range          92458 non-null  float64
 22  dist_to_recent_high   92458 non-null  float64
 23  dist_to_recent_low    92458 non-null  float64
 24  body_to_range         86995 non-null  float64
 25  tx_density            92477 non-null  float64
 26  vwap_pullback         92476 non-null  float64
 27  vol_shock             92477 non-null  int32
 28  price_reaction_next   92476 non-null  float64
dtypes: datetime64[ns](1), float64(24), int32(3), int64(1)
memory usage: 20.1 MB

In [45]:
df.dropna(inplace=True)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 86977 entries, 19 to 27532
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             86977 non-null  datetime64[ns]
 1   open                  86977 non-null  float64
 2   high                  86977 non-null  float64
 3   low                   86977 non-null  float64
 4   close                 86977 non-null  float64
 5   volume                86977 non-null  float64
 6   vwap                  86977 non-null  float64
 7   transactions          86977 non-null  int64
 8   vol/trans             86977 non-null  float64
 9   RVOL                  86977 non-null  float64
 10  VROC                  86977 non-null  float64
 11  spread_vol            86977 non-null  float64
 12  vwap_dev              86977 non-null  float64
 13  vol_per_tx            86977 non-null  float64
 14  VPI                   86977 non-null  float64
 15  accum_dist_vwap       86977 non-null  float64
 16  vol_spike             86977 non-null  int32
 17  climax_bar            86977 non-null  int32
 18  micro_trend_slope     86977 non-null  float64
 19  seconds_diff          86977 non-null  float64
 20  price_change_per_sec  86977 non-null  float64
 21  pos_in_range          86977 non-null  float64
 22  dist_to_recent_high   86977 non-null  float64
 23  dist_to_recent_low    86977 non-null  float64
 24  body_to_range         86977 non-null  float64
 25  tx_density            86977 non-null  float64
 26  vwap_pullback         86977 non-null  float64
 27  vol_shock             86977 non-null  int32
 28  price_reaction_next   86977 non-null  float64
dtypes: datetime64[ns](1), float64(24), int32(3), int64(1)
memory usage: 18.9 MB

In [47]:
# تحويل العمود الزمني إلى datetime إذا مش محوّل
df['timestamp'] = pd.to_datetime(df['timestamp'])

# حساب الفرق بالدقائق بين الصف الحالي والسابق
df['minutes_diff'] = (df['timestamp'] - df['timestamp'].shift(1)).dt.total_seconds() / 60

In [48]:
df

,timestamp,open,high,low,close,volume,vwap,transactions,vol/trans,RVOL,...,price_change_per_sec,pos_in_range,dist_to_recent_high,dist_to_recent_low,body_to_range,tx_density,vwap_pullback,vol_shock,price_reaction_next,minutes_diff
19,2023-08-07 09:35:00,183.0900,183.17,183.0900,183.1700,2771.0,183.1014,99,27.989899,0.432158,...,0.000400,0.663158,0.3200,0.6300,1.000000,0.035727,0.000281,0,-0.0500,NaN
20,2023-08-07 09:40:00,183.1900,183.20,183.1000,183.1200,7035.0,183.1682,180,39.083333,1.247429,...,-0.000167,0.616667,0.2300,0.3700,0.700000,0.025586,-0.000010,0,-0.0200,5.0
21,2023-08-07 09:45:00,183.1000,183.10,183.0700,183.1000,1832.0,183.0765,89,20.584270,0.373958,...,-0.000067,0.777778,0.1000,0.3500,0.000000,0.048581,-0.000238,0,-0.0800,5.0
22,2023-08-07 09:50:00,183.0300,183.10,183.0200,183.0200,4599.0,183.0324,99,46.454545,1.065829,...,-0.000267,0.600000,0.1800,0.2700,0.125000,0.021526,-0.000369,0,-0.1600,5.0
23,2023-08-07 09:55:00,183.0000,183.04,182.8500,182.8600,4196.0,182.9688,200,20.980000,0.967077,...,-0.000533,0.244444,0.3400,0.1100,0.736842,0.047664,-0.000280,0,0.0200,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27528,2025-08-05 23:30:00,202.8000,202.80,202.7000,202.7000,1990.0,202.7369,100,19.900000,0.666120,...,-0.000167,0.272727,0.2400,0.0900,1.000000,0.050251,-0.000065,0,0.0071,5.0
27529,2025-08-05 23:35:00,202.7889,202.80,202.7001,202.7071,971.0,202.7364,20,48.550000,0.397837,...,0.000024,0.294242,0.2329,0.0971,0.818819,0.020597,0.000180,0,0.0017,5.0
27530,2025-08-05 23:40:00,202.7200,202.79,202.7088,202.7088,676.0,202.7459,28,24.142857,0.283171,...,0.000006,0.299394,0.2312,0.0988,0.137931,0.041420,0.000191,0,0.0212,5.0
27531,2025-08-05 23:45:00,202.7900,202.86,202.7200,202.7300,2508.0,202.7997,86,29.162791,1.142493,...,0.000071,0.480000,0.1300,0.1200,0.428571,0.034290,0.000448,0,0.0699,5.0
27532,2025-08-05 23:50:00,202.7300,202.80,202.7300,202.7999,2763.0,202.7801,37,74.675676,1.329004,...,0.000233,0.738696,0.0601,0.1699,0.998571,0.013391,0.000247,0,0.0001,5.0

In [54]:
df['minutes_diff'].describe()

count    86976.000000
mean        12.079367
std        129.044794
min          5.000000
25%          5.000000
50%          5.000000
75%          5.000000
max       4985.000000
Name: minutes_diff, dtype: float64

In [55]:
# الفرق بين سعر الفتح الحالي وسعر الإغلاق السابق
df['open_vs_prev_close'] = df['open'] - df['close'].shift(1)

In [57]:
df.dropna(inplace=True)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 86976 entries, 20 to 27532
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             86976 non-null  datetime64[ns]
 1   open                  86976 non-null  float64
 2   high                  86976 non-null  float64
 3   low                   86976 non-null  float64
 4   close                 86976 non-null  float64
 5   volume                86976 non-null  float64
 6   vwap                  86976 non-null  float64
 7   transactions          86976 non-null  int64
 8   vol/trans             86976 non-null  float64
 9   RVOL                  86976 non-null  float64
 10  VROC                  86976 non-null  float64
 11  spread_vol            86976 non-null  float64
 12  vwap_dev              86976 non-null  float64
 13  vol_per_tx            86976 non-null  float64
 14  VPI                   86976 non-null  float64
 15  accum_dist_vwap       86976 non-null  float64
 16  vol_spike             86976 non-null  int32
 17  climax_bar            86976 non-null  int32
 18  micro_trend_slope     86976 non-null  float64
 19  seconds_diff          86976 non-null  float64
 20  price_change_per_sec  86976 non-null  float64
 21  pos_in_range          86976 non-null  float64
 22  dist_to_recent_high   86976 non-null  float64
 23  dist_to_recent_low    86976 non-null  float64
 24  body_to_range         86976 non-null  float64
 25  tx_density            86976 non-null  float64
 26  vwap_pullback         86976 non-null  float64
 27  vol_shock             86976 non-null  int32
 28  price_reaction_next   86976 non-null  float64
 29  minutes_diff          86976 non-null  float64
 30  open_vs_prev_close    86976 non-null  float64
dtypes: datetime64[ns](1), float64(26), int32(3), int64(1)
memory usage: 20.2 MB

In [60]:
df['vwap_distance'] = df['close'] - df['vwap']

In [61]:
df['vol_change_pct'] = (df['volume'] - df['volume'].shift(1)) / df['volume'].shift(1) * 100

In [63]:
df.dropna(inplace=True)

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 86975 entries, 21 to 27532
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             86975 non-null  datetime64[ns]
 1   open                  86975 non-null  float64
 2   high                  86975 non-null  float64
 3   low                   86975 non-null  float64
 4   close                 86975 non-null  float64
 5   volume                86975 non-null  float64
 6   vwap                  86975 non-null  float64
 7   transactions          86975 non-null  int64
 8   vol/trans             86975 non-null  float64
 9   RVOL                  86975 non-null  float64
 10  VROC                  86975 non-null  float64
 11  spread_vol            86975 non-null  float64
 12  vwap_dev              86975 non-null  float64
 13  vol_per_tx            86975 non-null  float64
 14  VPI                   86975 non-null  float64
 15  accum_dist_vwap       86975 non-null  float64
 16  vol_spike             86975 non-null  int32
 17  climax_bar            86975 non-null  int32
 18  micro_trend_slope     86975 non-null  float64
 19  seconds_diff          86975 non-null  float64
 20  price_change_per_sec  86975 non-null  float64
 21  pos_in_range          86975 non-null  float64
 22  dist_to_recent_high   86975 non-null  float64
 23  dist_to_recent_low    86975 non-null  float64
 24  body_to_range         86975 non-null  float64
 25  tx_density            86975 non-null  float64
 26  vwap_pullback         86975 non-null  float64
 27  vol_shock             86975 non-null  int32
 28  price_reaction_next   86975 non-null  float64
 29  minutes_diff          86975 non-null  float64
 30  open_vs_prev_close    86975 non-null  float64
 31  vwap_distance         86975 non-null  float64
 32  vol_change_pct        86975 non-null  float64
dtypes: datetime64[ns](1), float64(28), int32(3), int64(1)
memory usage: 21.6 MB

In [74]:
# استخراج التاريخ من التايم ستامب
df['date'] = df['timestamp'].dt.date

# أعلى سعر لليوم الحالي + حجم الشمعة عنده
high_today_info = df.loc[df.groupby('date')['high'].idxmax(), ['date', 'high', 'volume']]
high_today_info = high_today_info.rename(columns={'high': 'high_today', 'volume': 'vol_at_high_today'})

# أقل سعر لليوم الحالي + حجم الشمعة عنده
low_today_info = df.loc[df.groupby('date')['low'].idxmin(), ['date', 'low', 'volume']]
low_today_info = low_today_info.rename(columns={'low': 'low_today', 'volume': 'vol_at_low_today'})

# دمج الأعمدة مع الجدول الأصلي
df = df.merge(high_today_info, on='date', how='left')
df = df.merge(low_today_info, on='date', how='left')

# الحصول على بيانات اليوم السابق
df['prev_date'] = df['date'].shift(1)
df['high_prev_day'] = df.groupby('date')['high_today'].shift(1)
df['vol_at_high_prev_day'] = df.groupby('date')['vol_at_high_today'].shift(1)
df['low_prev_day'] = df.groupby('date')['low_today'].shift(1)
df['vol_at_low_prev_day'] = df.groupby('date')['vol_at_low_today'].shift(1)

MergeError: Passing 'suffixes' which cause duplicate columns {'high_today_x'} is not allowed.

In [73]:
df

,timestamp,open,high,low,close,volume,vwap,transactions,vol/trans,RVOL,...,low_prev_day,high_today_y,vol_at_high_today_x,low_today_y,vol_at_low_today_x,prev_date,high_today,vol_at_high_today_y,low_today,vol_at_low_today_y
0,2023-08-07 09:45:00,183.10,183.10,183.07,183.1000,1832.0,183.0765,89,20.584270,0.373958,...,NaN,183.88,122772.0,177.350,1224218.0,None,183.88,122772.0,177.35,1224218.0
1,2023-08-07 09:45:00,183.10,183.10,183.07,183.1000,1832.0,183.0765,89,20.584270,0.373958,...,NaN,183.88,122772.0,178.460,449479.0,2023-08-07,183.88,122772.0,177.35,1224218.0
2,2023-08-07 09:45:00,183.10,183.10,183.07,183.1000,1832.0,183.0765,89,20.584270,0.373958,...,NaN,183.88,122772.0,178.545,975173.0,2023-08-07,183.88,122772.0,177.35,1224218.0
3,2023-08-07 09:45:00,183.10,183.10,183.07,183.1000,1832.0,183.0765,89,20.584270,0.373958,...,NaN,182.66,2520138.0,177.350,1224218.0,2023-08-07,183.88,122772.0,177.35,1224218.0
4,2023-08-07 09:45:00,183.10,183.10,183.07,183.1000,1832.0,183.0765,89,20.584270,0.373958,...,NaN,182.66,2520138.0,178.460,449479.0,2023-08-07,183.88,122772.0,177.35,1224218.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591313,2025-08-05 23:45:00,202.79,202.86,202.72,202.7300,2508.0,202.7997,86,29.162791,1.142493,...,201.675,205.34,620756.0,202.160,1882215.0,2025-08-05,205.34,620756.0,202.16,1882215.0
591314,2025-08-05 23:50:00,202.73,202.80,202.73,202.7999,2763.0,202.7801,37,74.675676,1.329004,...,201.675,203.89,1031.0,202.640,1634.0,2025-08-05,205.34,620756.0,202.16,1882215.0
591315,2025-08-05 23:50:00,202.73,202.80,202.73,202.7999,2763.0,202.7801,37,74.675676,1.329004,...,201.675,203.89,1031.0,202.160,1882215.0,2025-08-05,205.34,620756.0,202.16,1882215.0
591316,2025-08-05 23:50:00,202.73,202.80,202.73,202.7999,2763.0,202.7801,37,74.675676,1.329004,...,201.675,205.34,620756.0,202.640,1634.0,2025-08-05,205.34,620756.0,202.16,1882215.0
591317,2025-08-05 23:50:00,202.73,202.80,202.73,202.7999,2763.0,202.7801,37,74.675676,1.329004,...,201.675,205.34,620756.0,202.160,1882215.0,2025-08-05,205.34,620756.0,202.16,1882215.0