In [150]:
import pandas as pd
df= pd.read_csv(r"C:\Users\Access\Documents\AI ROBOT\XAUUSD_Candlestick_1_M_BID_2020-1-1_2024-12-31.csv")

In [151]:
df=df.drop(columns='Volume')

In [152]:
import pandas as pd

# تحويل العمود الزمني إلى نوع datetime وتعيينه كمؤشر
df['Gmt time'] = pd.to_datetime(df['Gmt time'])
df.set_index('Gmt time', inplace=True)

# تحويل البيانات من 1 دقيقة إلى 5 دقائق
df_5m = df.resample('5T').agg({
    'Open': 'first',   # أول سعر افتتاح في الفاصل الزمني
    'High': 'max',     # أعلى سعر في الفاصل الزمني
    'Low': 'min',      # أقل سعر في الفاصل الزمني
    'Close': 'last'    # آخر سعر إغلاق في الفاصل الزمني
})

# عرض النتيجة
print(df_5m)

                         Open      High       Low     Close
Gmt time
2020-01-01 00:00:00  1516.915  1516.915  1516.915  1516.915
2020-01-01 00:05:00  1516.915  1516.915  1516.915  1516.915
2020-01-01 00:10:00  1516.915  1516.915  1516.915  1516.915
2020-01-01 00:15:00  1516.915  1516.915  1516.915  1516.915
2020-01-01 00:20:00  1516.915  1516.915  1516.915  1516.915
...                       ...       ...       ...       ...
2024-12-31 23:35:00  2624.255  2624.255  2624.255  2624.255
2024-12-31 23:40:00  2624.255  2624.255  2624.255  2624.255
2024-12-31 23:45:00  2624.255  2624.255  2624.255  2624.255
2024-12-31 23:50:00  2624.255  2624.255  2624.255  2624.255
2024-12-31 23:55:00  2624.255  2624.255  2624.255  2624.255

[526176 rows x 4 columns]

C:\Users\Access\AppData\Local\Temp\ipykernel_13016\422809626.py:8: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  df_5m = df.resample('5T').agg({

In [153]:
df_5m=df_5m.reset_index(drop=False)

In [154]:
import pandas as pd

df = df_5m.copy()

# تعريف دالة التحقق من الشمعة الكبيرة (تبقى كما هي)
def is_large_body(candle):
    body = abs(candle['Open'] - candle['Close'])
    lower_shadow = abs(candle['Low'] - min(candle['Open'], candle['Close']))
    upper_shadow = abs(candle['High'] - max(candle['Open'], candle['Close']))
    return (body * 2) > (lower_shadow + upper_shadow)

# تعديل دالة الهامر لتصبح شمعة Shooting Star (مقلوبة)
def is_shooting_star(candle):
    body = abs(candle['Open'] - candle['Close'])
    upper_shadow = abs(candle['High'] - max(candle['Open'], candle['Close']))
    lower_shadow = abs(candle['Low'] - min(candle['Open'], candle['Close']))
    return upper_shadow > 1 * body and lower_shadow < body

# تعديل دالة الصفقة لصفقات البيع
def calculate_sell_trade_shooting_star(row, df, tp_multiplier=1, sl_multiplier=0.5):
    idx = row.name
    if idx == df.index[0]:
        return 0, None, None
    
    first_candle = df.loc[df.index[df.index.get_loc(idx) - 1]]
    second_candle = row
    
    # الشرط المعكوس: شمعة صاعدة كبيرة تليها شمعة Shooting Star
    if is_large_body(first_candle) and first_candle['Open'] < first_candle['Close'] and is_shooting_star(second_candle) and second_candle['Open'] > second_candle['Close']:
        points = abs(first_candle['Open'] - first_candle['Close'])
        #take_profit = second_candle['Close'] - (points * tp_multiplier)
        stop_loss = second_candle['Close'] + (points * sl_multiplier)
        take_profit =  second_candle['Close'] - (tp_multiplier*abs(stop_loss - second_candle['Close']))

        return 1, take_profit, stop_loss
    
    return 0, None, None

# تطبيق الأعمدة الجديدة للصفقات البيعية
df['sell_trade_shooting'], df['tp_sell_shooting'], df['sl_sell_shooting'] = zip(*df.apply(
    lambda row: calculate_sell_trade_shooting_star(row, df), axis=1))

# تحديد نوع الصفقة للبيع
df['trade_type_shooting'] = df.apply(lambda row: -1 if row['sell_trade_shooting'] == 1 else 0, axis=1)

# دمج أعمدة TP و SL
df['tp_shooting'] = df.apply(lambda row: row['tp_sell_shooting'] if row['trade_type_shooting'] == -1 else None, axis=1)
df['sl_shooting'] = df.apply(lambda row: row['sl_sell_shooting'] if row['trade_type_shooting'] == -1 else None, axis=1)


# تعديل دالة تحديد نتيجة الصفقة للبيع
def determine_trade_result_shooting(row, df):
    idx = row.name
    if row['trade_type_shooting'] == -1:  # صفقة بيع
        for i in range(df.index.get_loc(idx) + 1, len(df)):
            future_row = df.iloc[i]
            if future_row['Low'] <= row['tp_shooting']:
                return 2  # رابحة
            elif future_row['High'] >= row['sl_shooting']:
                return 1  # خاسرة
    return 0  # لا توجد نتيجة
'''

# دالة لتحديد حالة الصفقة الشرائية
def determine_trade_result_shooting(row, df):
    idx = row.name  # الفهرس الزمني (Timestamp)
    if row['trade_type_shooting'] == -1:  # صفقة شراء
        for i in range(df.index.get_loc(idx) + 1, len(df)):
            future_row = df.iloc[i]
            if future_row['High'] >= row['tp_shooting']:
                return 2  # رابحة
            elif future_row['Low'] <= row['sl_shooting']:
                return 1  # خاسرة
    return 0  # لا توجد نتيجة

'''
# تطبيق دالة النتائج
df['trade_result_shooting'] = df.apply(lambda row: determine_trade_result_shooting(row, df), axis=1)

# عرض النتائج
print(df[['Gmt time','Open', 'High', 'Low', 'Close', 'trade_type_shooting', 'trade_result_shooting', 'tp_shooting', 'sl_shooting']])

                  Gmt time      Open      High       Low     Close  \
0      2020-01-01 00:00:00  1516.915  1516.915  1516.915  1516.915
1      2020-01-01 00:05:00  1516.915  1516.915  1516.915  1516.915
2      2020-01-01 00:10:00  1516.915  1516.915  1516.915  1516.915
3      2020-01-01 00:15:00  1516.915  1516.915  1516.915  1516.915
4      2020-01-01 00:20:00  1516.915  1516.915  1516.915  1516.915
...                    ...       ...       ...       ...       ...
526171 2024-12-31 23:35:00  2624.255  2624.255  2624.255  2624.255
526172 2024-12-31 23:40:00  2624.255  2624.255  2624.255  2624.255
526173 2024-12-31 23:45:00  2624.255  2624.255  2624.255  2624.255
526174 2024-12-31 23:50:00  2624.255  2624.255  2624.255  2624.255
526175 2024-12-31 23:55:00  2624.255  2624.255  2624.255  2624.255

        trade_type_shooting  trade_result_shooting  tp_shooting  sl_shooting
0                         0                      0          NaN          NaN
1                         0                      0          NaN          NaN
2                         0                      0          NaN          NaN
3                         0                      0          NaN          NaN
4                         0                      0          NaN          NaN
...                     ...                    ...          ...          ...
526171                    0                      0          NaN          NaN
526172                    0                      0          NaN          NaN
526173                    0                      0          NaN          NaN
526174                    0                      0          NaN          NaN
526175                    0                      0          NaN          NaN

[526176 rows x 9 columns]

In [143]:
df = df[df['trade_type_shooting'] != 0]

In [144]:
df = df[['Gmt time','Open', 'High', 'Low', 'Close', 'trade_type_shooting', 'trade_result_shooting', 'tp_shooting', 'sl_shooting']]

In [145]:
df

,Gmt time,Open,High,Low,Close,trade_type_shooting,trade_result_shooting,tp_shooting,sl_shooting
330,2020-01-02 03:30:00,1520.295,1520.435,1520.185,1520.215,-1,1,1520.1250,1520.3050
361,2020-01-02 06:05:00,1520.505,1520.768,1520.345,1520.405,-1,1,1520.2200,1520.5900
509,2020-01-02 18:25:00,1525.648,1525.875,1525.485,1525.505,-1,2,1525.2350,1525.7750
760,2020-01-03 15:20:00,1550.195,1550.988,1549.785,1549.958,-1,2,1549.5845,1550.3315
787,2020-01-03 17:35:00,1548.488,1548.748,1548.238,1548.348,-1,1,1548.1830,1548.5130
...,...,...,...,...,...,...,...,...,...
525784,2024-12-30 15:20:00,2604.455,2605.755,2603.195,2603.605,-1,2,2603.2450,2603.9650
525810,2024-12-30 17:30:00,2603.035,2603.665,2602.655,2602.815,-1,2,2602.3550,2603.2750
525899,2024-12-31 00:55:00,2607.948,2608.505,2607.335,2607.585,-1,2,2607.3585,2607.8115
525973,2024-12-31 07:05:00,2608.498,2609.005,2608.198,2608.345,-1,2,2607.8935,2608.7965
526042,2024-12-31 12:50:00,2611.975,2612.548,2611.485,2611.695,-1,2,2610.8450,2612.5450

In [146]:
# حساب التكرارات والنسب المئوية
result = df['trade_result_shooting'].value_counts().sort_index()
percent = df['trade_result_shooting'].value_counts(normalize=True).sort_index() * 100

# دمج النتائج في DataFrame
result_df = pd.DataFrame({
    'Count': result,
    'Percentage (%)': percent.round(1)})

result_df['Percentage (%)'] = result_df['Percentage (%)'].astype(str) + '%'

print(result_df)

                       Count Percentage (%)
trade_result_shooting
1                       1518          39.5%
2                       2325          60.5%

In [135]:
# حساب التكرارات والنسب المئوية
result = df['trade_result_shooting'].value_counts().sort_index()
percent = df['trade_result_shooting'].value_counts(normalize=True).sort_index() * 100

# دمج النتائج في DataFrame
result_df = pd.DataFrame({
    'Count': result,
    'Percentage (%)': percent.round(1)})

result_df['Percentage (%)'] = result_df['Percentage (%)'].astype(str) + '%'

print(result_df)

                       Count Percentage (%)
trade_result_shooting
1                        978          39.0%
2                       1531          61.0%

In [147]:
import pandas as pd

# تصفية الصفقات التي تحتوي على نتائج
df = df[df['trade_result_shooting'] != 0]

# استخراج التاريخ فقط
df['Gmt date'] = df['Gmt time'].dt.date

# تصنيف الصفقات
df['trade_type'] = df['trade_result_shooting'].apply(lambda x: 'رابحة' if x == 2 else 'خاسرة')

# حساب عدد الصفقات لكل يوم
daily_trades = df.groupby(['Gmt date', 'trade_type']).size().unstack(fill_value=0)

# إعادة تسمية الأعمدة
daily_trades = daily_trades.rename(columns={'رابحة': 'Winning Trades', 'خاسرة': 'Losing Trades'})

# إنشاء نطاق تواريخ شامل من البيانات الأصلية
start_date = df['Gmt time'].min().normalize()
end_date = df['Gmt time'].max().normalize()
all_dates = pd.date_range(start=start_date, end=end_date, freq='D')

# تحويل الفهرس إلى تنسيق تاريخي
daily_trades.index = pd.to_datetime(daily_trades.index)

# إعادة الفهرس ليشمل جميع التواريخ
daily_trades = daily_trades.reindex(all_dates, fill_value=0)

# تصفية أيام السبت (5) والأحد (6) باستخدام weekday
daily_trades = daily_trades[daily_trades.index.weekday < 5]  # 0-4 = من الاثنين إلى الجمعة

# إضافة عمود الصفقات الكلية
daily_trades['Total Trades'] = daily_trades['Winning Trades'] + daily_trades['Losing Trades']

# إعادة تنسيق الفهرس لعرضه كتواريخ بدون وقت
daily_trades.index = daily_trades.index.date

print(daily_trades)

trade_type  Losing Trades  Winning Trades  Total Trades
2020-01-02              2               1             3
2020-01-03              1               1             2
2020-01-06              1               2             3
2020-01-07              1               4             5
2020-01-08              2               1             3
...                   ...             ...           ...
2024-12-25              0               0             0
2024-12-26              2               2             4
2024-12-27              1               1             2
2024-12-30              0               2             2
2024-12-31              0               3             3

[1304 rows x 3 columns]

In [149]:
daily_trades.describe().round(1).drop(['count','std'])

trade_type  Losing Trades  Winning Trades  Total Trades
mean                  1.2             1.8           2.9
min                   0.0             0.0           0.0
25%                   0.0             1.0           2.0
50%                   1.0             2.0           3.0
75%                   2.0             3.0           4.0
max                   6.0             7.0           9.0

In [12]:
daily_trades.to_csv(r"C:\Users\Access\Documents\AI\XAUUSD_5m_trade_result_shooting.csv", index=True)