In [1]:
import pandas as pd

# المسار الخاص بالملف
file_path = r"C:\Users\Access\Downloads\EURUSD_Ticks.csv"

# قراءة البيانات من الملف
df = pd.read_csv(file_path)

In [2]:
df

                        Gmt time      Ask      Bid    AskVolume     BidVolume
0        03.08.2021 00:00:00.179  1.18743  1.18738  819999.9928  2.890000e+06
1        03.08.2021 00:00:00.500  1.18741  1.18739  750000.0000  2.890000e+06
2        03.08.2021 00:00:00.602  1.18741  1.18740  750000.0000  1.900000e+05
3        03.08.2021 00:00:00.704  1.18743  1.18739  750000.0000  1.200000e+06
4        03.08.2021 00:00:00.980  1.18744  1.18739  100000.0015  4.500000e+05
...                          ...      ...      ...          ...           ...
1020878  06.09.2021 23:58:59.205  1.18738  1.18735  750000.0000  1.000000e+05
1020879  06.09.2021 23:59:13.928  1.18737  1.18734  750000.0000  8.200000e+05
1020880  06.09.2021 23:59:14.182  1.18736  1.18732  750000.0000  3.450000e+06
1020881  06.09.2021 23:59:16.813  1.18735  1.18732  750000.0000  1.570000e+06
1020882  06.09.2021 23:59:49.846  1.18735  1.18731  750000.0000  1.850000e+06

[1020883 rows x 5 columns]