In [6]:
!pip install pandas pandas_ta numpy matplotlib scipy backtesting mplfinance

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: pandas_ta in c:\users\access\appdata\roaming\python\python312\site-packages (0.3.14b0)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (1.26.4)
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\lib\site-packages (3.8.4)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (1.13.1)
Requirement already satisfied: backtesting in c:\users\access\appdata\roaming\python\python312\site-packages (0.3.3)
Collecting mplfinance
  Downloading mplfinance-0.12.10b0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\access\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\access\appdata\roaming\python\python312\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: bokeh>=1.4.0 in c:\programdata\anaconda3\lib\site-packages (from backtesting) (3.4.1)
Requirement already satisfied: Jinja2>=2.9 in c:\programdata\anaconda3\lib\site-packages (from bokeh>=1.4.0->backtesting) (3.1.4)
Requirement already satisfied: PyYAML>=3.10 in c:\programdata\anaconda3\lib\site-packages (from bokeh>=1.4.0->backtesting) (6.0.1)
Requirement already satisfied: tornado>=6.2 in c:\users\access\appdata\roaming\python\python312\site-packages (from bokeh>=1.4.0->backtesting) (6.4.1)
Requirement already satisfied: xyzservices>=2021.09.1 in c:\programdata\anaconda3\lib\site-packages (from bokeh>=1.4.0->backtesting) (2022.9.0)
Requirement already satisfied: six>=1.5 in c:\users\access\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from Jinja2>=2.9->bokeh>=1.4.0->backtesting) (2.1.3)
Downloading mplfinance-0.12.10b0-py3-none-any.whl (75 kB)
   ---------------------------------------- 0.0/75.0 kB ? eta -:--:--
   ---------------- ----------------------- 30.7/75.0 kB 660.6 kB/s eta 0:00:01
   --------------------- ------------------ 41.0/75.0 kB 653.6 kB/s eta 0:00:01
   ---------------------------------------- 75.0/75.0 kB 518.2 kB/s eta 0:00:00
Installing collected packages: mplfinance
Successfully installed mplfinance-0.12.10b0

In [37]:
import pandas as pd

# المسار الخاص بالملف
file_path = r"C:\Users\Access\Downloads\EURUSD_Ticks.csv"

# قراءة البيانات من الملف
df = pd.read_csv(file_path)

In [44]:
df[:]

                        Gmt time      Ask      Bid    AskVolume     BidVolume
0        03.08.2021 00:00:00.179  1.18743  1.18738  819999.9928  2.890000e+06
1        03.08.2021 00:00:00.500  1.18741  1.18739  750000.0000  2.890000e+06
2        03.08.2021 00:00:00.602  1.18741  1.18740  750000.0000  1.900000e+05
3        03.08.2021 00:00:00.704  1.18743  1.18739  750000.0000  1.200000e+06
4        03.08.2021 00:00:00.980  1.18744  1.18739  100000.0015  4.500000e+05
...                          ...      ...      ...          ...           ...
1020878  06.09.2021 23:58:59.205  1.18738  1.18735  750000.0000  1.000000e+05
1020879  06.09.2021 23:59:13.928  1.18737  1.18734  750000.0000  8.200000e+05
1020880  06.09.2021 23:59:14.182  1.18736  1.18732  750000.0000  3.450000e+06
1020881  06.09.2021 23:59:16.813  1.18735  1.18732  750000.0000  1.570000e+06
1020882  06.09.2021 23:59:49.846  1.18735  1.18731  750000.0000  1.850000e+06

[1020883 rows x 5 columns]

In [47]:
drrr = df 
drrr['Open'] = drrr['Ask']  # أو استخدم سعر الـ ask في بداية الفترة
drrr['Close'] = (drrr['Ask'] + drrr['Bid']) / 2  # أو استخدم df['ask'] أو df['bid'] حسب الحاجة
drrr['High'] = drrr[['Ask', 'Bid']].max(axis=1)  # أعلى سعر
drrr['Low'] = drrr[['Ask', 'Bid']].min(axis=1)    # أقل سعر

In [48]:
drrr

,Gmt time,Ask,Bid,AskVolume,BidVolume,Open,Close,High,Low
0,03.08.2021 00:00:00.179,1.18743,1.18738,819999.9928,2.890000e+06,1.18743,1.187405,1.18743,1.18738
1,03.08.2021 00:00:00.500,1.18741,1.18739,750000.0000,2.890000e+06,1.18741,1.187400,1.18741,1.18739
2,03.08.2021 00:00:00.602,1.18741,1.18740,750000.0000,1.900000e+05,1.18741,1.187405,1.18741,1.18740
3,03.08.2021 00:00:00.704,1.18743,1.18739,750000.0000,1.200000e+06,1.18743,1.187410,1.18743,1.18739
4,03.08.2021 00:00:00.980,1.18744,1.18739,100000.0015,4.500000e+05,1.18744,1.187415,1.18744,1.18739
...,...,...,...,...,...,...,...,...,...
1020878,06.09.2021 23:58:59.205,1.18738,1.18735,750000.0000,1.000000e+05,1.18738,1.187365,1.18738,1.18735
1020879,06.09.2021 23:59:13.928,1.18737,1.18734,750000.0000,8.200000e+05,1.18737,1.187355,1.18737,1.18734
1020880,06.09.2021 23:59:14.182,1.18736,1.18732,750000.0000,3.450000e+06,1.18736,1.187340,1.18736,1.18732
1020881,06.09.2021 23:59:16.813,1.18735,1.18732,750000.0000,1.570000e+06,1.18735,1.187335,1.18735,1.18732
1020882,06.09.2021 23:59:49.846,1.18735,1.18731,750000.0000,1.850000e+06,1.18735,1.187330,1.18735,1.18731