In [100]:
import pandas as pd
df= pd.read_csv(r"C:\Users\Access\Documents\AI ROBOT\XAUUSD_Candlestick_1_M_BID_2020-1-1_2024-12-31.csv")

In [101]:
df=df.drop(columns='Volume')

In [102]:
import pandas as pd

# تحويل العمود الزمني إلى نوع datetime وتعيينه كمؤشر
df['Gmt time'] = pd.to_datetime(df['Gmt time'])
df.set_index('Gmt time', inplace=True)

# تحويل البيانات من 1 دقيقة إلى 5 دقائق
df_5m = df.resample('5T').agg({
    'Open': 'first',   # أول سعر افتتاح في الفاصل الزمني
    'High': 'max',     # أعلى سعر في الفاصل الزمني
    'Low': 'min',      # أقل سعر في الفاصل الزمني
    'Close': 'last'    # آخر سعر إغلاق في الفاصل الزمني
})

# عرض النتيجة
print(df_5m)

C:\Users\Access\AppData\Local\Temp\ipykernel_37528\422809626.py:8: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  df_5m = df.resample('5T').agg({

                         Open      High       Low     Close
Gmt time
2020-01-01 00:00:00  1516.915  1516.915  1516.915  1516.915
2020-01-01 00:05:00  1516.915  1516.915  1516.915  1516.915
2020-01-01 00:10:00  1516.915  1516.915  1516.915  1516.915
2020-01-01 00:15:00  1516.915  1516.915  1516.915  1516.915
2020-01-01 00:20:00  1516.915  1516.915  1516.915  1516.915
...                       ...       ...       ...       ...
2024-12-31 23:35:00  2624.255  2624.255  2624.255  2624.255
2024-12-31 23:40:00  2624.255  2624.255  2624.255  2624.255
2024-12-31 23:45:00  2624.255  2624.255  2624.255  2624.255
2024-12-31 23:50:00  2624.255  2624.255  2624.255  2624.255
2024-12-31 23:55:00  2624.255  2624.255  2624.255  2624.255

[526176 rows x 4 columns]

In [103]:
df_5m=df_5m.reset_index(drop=False)

In [104]:
import pandas as pd

# افترض أن df_5m هو DataFrame موجود مسبقًا
df = df_5m

# تعريف دالة التحقق من الشمعة الكبيرة مقارنة بالظلال
def is_large_body(candle):
    body = abs(candle['Open'] - candle['Close'])
    lower_shadow = abs(candle['Low'] - min(candle['Open'], candle['Close']))
    upper_shadow = abs(candle['High'] - max(candle['Open'], candle['Close']))
    return body > (lower_shadow + upper_shadow)

# تعريف دالة التحقق من شمعة الهامر
def is_hammer(candle):
    body = abs(candle['Open'] - candle['Close'])
    lower_shadow = abs(candle['Low'] - min(candle['Open'], candle['Close']))
    upper_shadow = abs(candle['High'] - max(candle['Open'], candle['Close']))
    return lower_shadow > 1 * body and upper_shadow < body

# دالة حساب صفقة شراء باستخدام الهامر
def calculate_buy_trade_hammer(row, df, tp_multiplier=2, sl_multiplier=1):
    idx = row.name  # الفهرس الزمني (Timestamp)
    if idx == df.index[0]:  # إذا كانت الشمعة الأولى، لا توجد صفقة
        return 0, None, None
    first_candle = df.loc[df.index[df.index.get_loc(idx) - 1]]  # الشمعة السابقة
    second_candle = row  # الشمعة الحالية
    if is_large_body(first_candle) and first_candle['Close'] < first_candle['Open'] and is_hammer(second_candle):
        points = abs(first_candle['Open'] - first_candle['Close'])
        take_profit = second_candle['Close'] + (points * tp_multiplier)
        stop_loss = second_candle['Low'] - (points * sl_multiplier)
        return 1, take_profit, stop_loss
    return 0, None, None

# تطبيق الأعمدة الجديدة للصفقات الشرائية
df['buy_trade_hammer'], df['tp_buy_hammer'], df['sl_buy_hammer'] = zip(*df.apply(lambda row: calculate_buy_trade_hammer(row, df), axis=1))

# تحديد نوع الصفقة للشراء
df['trade_type_hammer'] = df.apply(lambda row: 1 if row['buy_trade_hammer'] == 1 else 0, axis=1)

# دمج أعمدة TP و SL للصفقات الشرائية
df['tp_hammer'] = df.apply(lambda row: row['tp_buy_hammer'] if row['trade_type_hammer'] == 1 else None, axis=1)
df['sl_hammer'] = df.apply(lambda row: row['sl_buy_hammer'] if row['trade_type_hammer'] == 1 else None, axis=1)

# دالة لتحديد حالة الصفقة الشرائية
def determine_trade_result_hammer(row, df):
    idx = row.name  # الفهرس الزمني (Timestamp)
    if row['trade_type_hammer'] == 1:  # صفقة شراء
        for i in range(df.index.get_loc(idx) + 1, len(df)):
            future_row = df.iloc[i]
            if future_row['High'] >= row['tp_hammer']:
                return 2  # رابحة
            elif future_row['Low'] <= row['sl_hammer']:
                return 1  # خاسرة
    return 0  # لا توجد نتيجة

# تطبيق دالة تحديد حالة الصفقة الشرائية
df['trade_result_hammer'] = df.apply(lambda row: determine_trade_result_hammer(row, df), axis=1)

























# حساب عمود الرصيد
current_balance = 1000  # رأس المال الابتدائي
balance = [current_balance] * len(df)  # تهيئة القائمة بنفس طول الداتافرام

for i in range(1, len(df)):
    previous_balance = balance[i-1]
    
    if df.iloc[i]['trade_result_hammer'] == 2:  # صفقة رابحة
        balance[i] = previous_balance + (previous_balance * 0.02)  # ربح 2%
    elif df.iloc[i]['trade_result_hammer'] == 1:  # صفقة خاسرة
        balance[i] = previous_balance - (previous_balance * 0.01)  # خسارة 1%
    else:
        balance[i] = previous_balance  # بدون تغيير

df['balance'] = balance

# عرض النتائج مع العمود الجديد
print(df[['Gmt time', 'Open', 'High', 'Low', 'Close', 'trade_type_hammer', 
          'trade_result_hammer', 'tp_hammer', 'sl_hammer', 'balance']])

                  Gmt time      Open      High       Low     Close  \
0      2020-01-01 00:00:00  1516.915  1516.915  1516.915  1516.915
1      2020-01-01 00:05:00  1516.915  1516.915  1516.915  1516.915
2      2020-01-01 00:10:00  1516.915  1516.915  1516.915  1516.915
3      2020-01-01 00:15:00  1516.915  1516.915  1516.915  1516.915
4      2020-01-01 00:20:00  1516.915  1516.915  1516.915  1516.915
...                    ...       ...       ...       ...       ...
526171 2024-12-31 23:35:00  2624.255  2624.255  2624.255  2624.255
526172 2024-12-31 23:40:00  2624.255  2624.255  2624.255  2624.255
526173 2024-12-31 23:45:00  2624.255  2624.255  2624.255  2624.255
526174 2024-12-31 23:50:00  2624.255  2624.255  2624.255  2624.255
526175 2024-12-31 23:55:00  2624.255  2624.255  2624.255  2624.255

        trade_type_hammer  trade_result_hammer  tp_hammer  sl_hammer  \
0                       0                    0        NaN        NaN
1                       0                    0        NaN        NaN
2                       0                    0        NaN        NaN
3                       0                    0        NaN        NaN
4                       0                    0        NaN        NaN
...                   ...                  ...        ...        ...
526171                  0                    0        NaN        NaN
526172                  0                    0        NaN        NaN
526173                  0                    0        NaN        NaN
526174                  0                    0        NaN        NaN
526175                  0                    0        NaN        NaN

             balance
0       1.000000e+03
1       1.000000e+03
2       1.000000e+03
3       1.000000e+03
4       1.000000e+03
...              ...
526171  1.161453e+23
526172  1.161453e+23
526173  1.161453e+23
526174  1.161453e+23
526175  1.161453e+23

[526176 rows x 10 columns]

In [105]:
df = df[['Gmt time', 'Open', 'High', 'Low', 'Close', 'trade_type_hammer', 
          'trade_result_hammer', 'tp_hammer', 'sl_hammer', 'balance']]

In [108]:
df = df[df['trade_type_hammer'] != 0]

In [109]:
df

,Gmt time,Open,High,Low,Close,trade_type_hammer,trade_result_hammer,tp_hammer,sl_hammer,balance
310,2020-01-02 01:50:00,1519.300,1519.408,1518.875,1519.365,1,1,1519.981,1518.567,9.900000e+02
335,2020-01-02 03:55:00,1520.208,1520.298,1520.115,1520.275,1,1,1520.655,1519.925,9.801000e+02
399,2020-01-02 09:15:00,1519.995,1520.265,1519.515,1520.205,1,2,1520.671,1519.282,9.997020e+02
422,2020-01-02 11:10:00,1521.505,1521.555,1521.228,1521.375,1,2,1521.881,1520.975,1.019696e+03
496,2020-01-02 17:20:00,1524.685,1524.685,1522.715,1524.605,1,2,1527.385,1521.325,1.040090e+03
...,...,...,...,...,...,...,...,...,...,...
525997,2024-12-31 09:05:00,2615.464,2615.955,2614.385,2615.854,1,1,2617.634,2613.495,1.105518e+23
526016,2024-12-31 10:40:00,2611.825,2612.205,2611.395,2612.078,1,2,2613.658,2610.605,1.127628e+23
526073,2024-12-31 15:25:00,2617.475,2618.355,2616.935,2617.965,1,2,2620.325,2615.755,1.150181e+23
526104,2024-12-31 18:00:00,2624.135,2625.205,2623.115,2625.125,1,2,2626.485,2622.435,1.173184e+23
526123,2024-12-31 19:35:00,2623.875,2624.095,2623.245,2623.635,1,1,2625.535,2622.295,1.161453e+23

In [110]:
# تحويل الأرقام إلى تنسيق عشري مع 2 منازل عشرية
df['balance'] = df['balance'].apply(lambda x: f"{x:.2f}")

C:\Users\Access\AppData\Local\Temp\ipykernel_37528\1525563271.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balance'] = df['balance'].apply(lambda x: f"{x:.2f}")

In [112]:
df[:60]

,Gmt time,Open,High,Low,Close,trade_type_hammer,trade_result_hammer,tp_hammer,sl_hammer,balance
310,2020-01-02 01:50:00,1519.300,1519.408,1518.875,1519.365,1,1,1519.981,1518.567,990.00
335,2020-01-02 03:55:00,1520.208,1520.298,1520.115,1520.275,1,1,1520.655,1519.925,980.10
399,2020-01-02 09:15:00,1519.995,1520.265,1519.515,1520.205,1,2,1520.671,1519.282,999.70
422,2020-01-02 11:10:00,1521.505,1521.555,1521.228,1521.375,1,2,1521.881,1520.975,1019.70
496,2020-01-02 17:20:00,1524.685,1524.685,1522.715,1524.605,1,2,1527.385,1521.325,1040.09
566,2020-01-02 23:10:00,1528.065,1528.268,1527.848,1528.268,1,2,1528.654,1527.655,1060.89
595,2020-01-03 01:35:00,1530.325,1530.555,1530.015,1530.508,1,2,1531.508,1529.515,1082.11
610,2020-01-03 02:50:00,1538.595,1538.995,1538.145,1538.975,1,2,1541.215,1537.025,1103.75
612,2020-01-03 03:00:00,1538.255,1538.775,1537.658,1538.648,1,2,1540.208,1536.878,1125.83
696,2020-01-03 10:00:00,1546.835,1546.955,1545.255,1546.268,1,2,1549.208,1543.785,1148.34
718,2020-01-03 11:50:00,1550.038,1550.138,1549.355,1549.818,1,1,1551.632,1548.448,1136.86
736,2020-01-03 13:20:00,1542.775,1542.868,1541.068,1542.128,1,2,1543.862,1540.201,1159.60
765,2020-01-03 15:45:00,1548.375,1548.388,1547.828,1548.288,1,2,1550.928,1546.508,1182.79
777,2020-01-03 16:45:00,1548.988,1549.838,1548.208,1549.658,1,1,1551.778,1547.148,1170.96
801,2020-01-03 18:45:00,1549.848,1550.275,1549.348,1550.275,1,1,1553.735,1547.618,1159.25
1562,2020-01-06 10:10:00,1575.635,1575.828,1575.015,1575.815,1,2,1576.995,1574.425,1182.44
1649,2020-01-06 17:25:00,1563.355,1563.588,1562.945,1563.488,1,2,1565.788,1561.795,1206.09
1681,2020-01-06 20:05:00,1564.605,1564.905,1564.295,1564.795,1,2,1565.195,1564.095,1230.21
1690,2020-01-06 20:50:00,1565.408,1565.655,1565.195,1565.565,1,1,1567.165,1564.395,1217.90
1728,2020-01-07 00:00:00,1563.695,1563.895,1562.798,1563.405,1,2,1564.519,1562.241,1242.26
1750,2020-01-07 01:50:00,1558.608,1558.668,1556.918,1558.265,1,2,1564.465,1553.818,1267.11
1770,2020-01-07 03:30:00,1559.275,1559.285,1559.078,1559.185,1,1,1560.125,1558.608,1254.44
1782,2020-01-07 04:30:00,1558.485,1558.825,1557.935,1558.825,1,2,1560.045,1557.325,1279.53
1842,2020-01-07 09:30:00,1564.478,1564.575,1563.198,1564.245,1,2,1565.625,1562.508,1305.12
1887,2020-01-07 13:15:00,1566.445,1567.055,1565.658,1566.905,1,1,1568.325,1564.948,1292.07
1908,2020-01-07 15:00:00,1568.885,1568.885,1565.448,1568.635,1,2,1571.621,1563.955,1317.91
1941,2020-01-07 17:45:00,1572.375,1572.725,1572.165,1572.565,1,1,1573.565,1571.665,1304.73
1951,2020-01-07 18:35:00,1571.748,1571.798,1571.508,1571.688,1,1,1573.448,1570.628,1291.68
2015,2020-01-07 23:55:00,1592.825,1595.355,1589.548,1594.955,1,2,1600.655,1586.698,1317.51
2037,2020-01-08 01:45:00,1593.125,1596.058,1590.478,1594.898,1,1,1611.338,1582.258,1304.34
2106,2020-01-08 07:30:00,1587.895,1588.815,1585.815,1588.445,1,1,1592.031,1584.022,1291.30
2108,2020-01-08 07:40:00,1587.275,1588.135,1586.115,1587.915,1,1,1590.169,1584.988,1278.38
2112,2020-01-08 08:00:00,1588.515,1588.878,1586.398,1587.825,1,1,1589.105,1585.758,1265.60
2118,2020-01-08 08:30:00,1585.185,1585.918,1584.465,1585.745,1,1,1587.851,1583.412,1252.94
2125,2020-01-08 09:05:00,1580.095,1580.768,1579.288,1580.755,1,2,1582.449,1578.441,1278.00
2140,2020-01-08 10:20:00,1581.548,1582.115,1580.965,1582.005,1,1,1587.399,1578.268,1265.22
2155,2020-01-08 11:35:00,1576.665,1577.375,1576.025,1577.165,1,1,1582.705,1573.255,1252.57
2171,2020-01-08 12:55:00,1576.395,1576.445,1573.415,1575.315,1,1,1578.175,1571.985,1240.04
2176,2020-01-08 13:20:00,1569.378,1570.608,1568.038,1570.608,1,2,1576.468,1565.108,1264.84
2247,2020-01-08 19:15:00,1554.195,1554.415,1553.735,1554.315,1,1,1556.195,1552.795,1252.20
2253,2020-01-08 19:45:00,1553.585,1553.735,1552.178,1552.895,1,2,1555.461,1550.895,1277.24
2277,2020-01-08 21:45:00,1555.805,1555.865,1555.368,1555.638,1,2,1556.738,1554.818,1302.78
2307,2020-01-09 00:15:00,1555.078,1555.218,1553.735,1554.495,1,2,1556.869,1552.548,1328.84
2368,2020-01-09 05:20:00,1558.205,1558.235,1557.055,1557.715,1,1,1558.969,1556.428,1315.55
2408,2020-01-09 08:40:00,1546.305,1546.635,1545.298,1546.525,1,2,1549.885,1543.618,1341.86
2450,2020-01-09 12:10:00,1546.958,1547.155,1546.408,1546.735,1,2,1547.929,1545.811,1368.70
2469,2020-01-09 13:45:00,1551.755,1551.755,1549.448,1550.745,1,1,1553.091,1548.275,1355.01
2485,2020-01-09 15:05:00,1550.628,1550.845,1549.555,1550.845,1,1,1552.871,1548.542,1341.46
2488,2020-01-09 15:20:00,1548.945,1549.335,1546.545,1548.365,1,2,1552.325,1544.565,1368.29
2494,2020-01-09 15:50:00,1547.345,1547.455,1544.745,1546.665,1,2,1548.185,1543.985,1395.66
2500,2020-01-09 16:20:00,1547.225,1548.008,1546.815,1547.625,1,2,1548.611,1546.322,1423.57
2544,2020-01-09 20:00:00,1552.635,1552.985,1552.345,1552.875,1,1,1554.015,1551.775,1409.34
2595,2020-01-10 00:15:00,1551.585,1551.665,1551.075,1551.355,1,1,1552.335,1550.585,1395.24
2666,2020-01-10 06:10:00,1547.345,1547.465,1546.908,1547.145,1,1,1547.851,1546.555,1381.29
2675,2020-01-10 06:55:00,1547.755,1547.845,1547.458,1547.825,1,2,1548.551,1547.095,1408.92
2725,2020-01-10 11:05:00,1548.500,1548.615,1547.945,1548.565,1,2,1549.115,1547.670,1437.09
2750,2020-01-10 13:10:00,1548.695,1548.935,1547.745,1548.275,1,2,1549.335,1547.215,1465.84
2753,2020-01-10 13:25:00,1548.315,1548.915,1547.215,1548.628,1,2,1550.134,1546.462,1495.15
2756,2020-01-10 13:40:00,1554.895,1555.255,1553.465,1554.405,1,1,1556.279,1552.528,1480.20
2792,2020-01-10 16:40:00,1559.685,1560.065,1558.848,1559.885,1,1,1561.365,1558.108,1465.40

In [113]:
df.to_csv(r"C:\Users\Access\Documents\AI\XAUUSD_5m_trade_result_ham_balance.csv", index=True)

In [94]:
import pandas as pd

df=df_5m

# تعريف دالة التحقق من الشمعة الكبيرة مقارنة بالظلال
def is_large_body(candle):
    body = abs(candle['Open'] - candle['Close'])
    lower_shadow = abs(candle['Low'] - min(candle['Open'], candle['Close']))
    upper_shadow = abs(candle['High'] - max(candle['Open'], candle['Close']))
    return body > (lower_shadow + upper_shadow)

# تعريف دالة التحقق من شمعة الهامر
def is_hammer(candle):
    body = abs(candle['Open'] - candle['Close'])
    lower_shadow = abs(candle['Low'] - min(candle['Open'], candle['Close']))
    upper_shadow = abs(candle['High'] - max(candle['Open'], candle['Close']))
    return lower_shadow > 1 * body and upper_shadow < body

# دالة حساب صفقة شراء باستخدام الهامر
def calculate_buy_trade_hammer(row, df, tp_multiplier=2, sl_multiplier=1):
    idx = row.name  # الفهرس الزمني (Timestamp)
    if idx == df.index[0]:  # إذا كانت الشمعة الأولى، لا توجد صفقة
        return 0, None, None
    first_candle = df.loc[df.index[df.index.get_loc(idx) - 1]]  # الشمعة السابقة
    second_candle = row  # الشمعة الحالية
    if is_large_body(first_candle) and first_candle['Close'] < first_candle['Open'] and is_hammer(second_candle):
        points = abs(first_candle['Open'] - first_candle['Close'])
        take_profit = second_candle['Close'] + (points * tp_multiplier)
        stop_loss = second_candle['Low'] - (points * sl_multiplier)
        return 1, take_profit, stop_loss
    return 0, None, None

# تطبيق الأعمدة الجديدة للصفقات الشرائية
df['buy_trade_hammer'], df['tp_buy_hammer'], df['sl_buy_hammer'] = zip(*df.apply(lambda row: calculate_buy_trade_hammer(row, df), axis=1))

# تحديد نوع الصفقة للشراء
df['trade_type_hammer'] = df.apply(lambda row: 1 if row['buy_trade_hammer'] == 1 else 0, axis=1)

# دمج أعمدة TP و SL للصفقات الشرائية
df['tp_hammer'] = df.apply(lambda row: row['tp_buy_hammer'] if row['trade_type_hammer'] == 1 else None, axis=1)
df['sl_hammer'] = df.apply(lambda row: row['sl_buy_hammer'] if row['trade_type_hammer'] == 1 else None, axis=1)

# دالة لتحديد حالة الصفقة الشرائية
def determine_trade_result_hammer(row, df):
    idx = row.name  # الفهرس الزمني (Timestamp)
    if row['trade_type_hammer'] == 1:  # صفقة شراء
        for i in range(df.index.get_loc(idx) + 1, len(df)):
            future_row = df.iloc[i]
            if future_row['High'] >= row['tp_hammer']:
                return 2  # رابحة
            elif future_row['Low'] <= row['sl_hammer']:
                return 1  # خاسرة
    return 0  # لا توجد نتيجة

# تطبيق دالة تحديد حالة الصفقة الشرائية
df['trade_result_hammer'] = df.apply(lambda row: determine_trade_result_hammer(row, df), axis=1)

# عرض الأعمدة المطلوبة للصفقات الشرائية
print(df[['Gmt time','Open', 'High', 'Low', 'Close', 'trade_type_hammer', 'trade_result_hammer', 'tp_hammer', 'sl_hammer']])

                  Gmt time      Open      High       Low     Close  \
0      2020-01-01 00:00:00  1516.915  1516.915  1516.915  1516.915
1      2020-01-01 00:05:00  1516.915  1516.915  1516.915  1516.915
2      2020-01-01 00:10:00  1516.915  1516.915  1516.915  1516.915
3      2020-01-01 00:15:00  1516.915  1516.915  1516.915  1516.915
4      2020-01-01 00:20:00  1516.915  1516.915  1516.915  1516.915
...                    ...       ...       ...       ...       ...
526171 2024-12-31 23:35:00  2624.255  2624.255  2624.255  2624.255
526172 2024-12-31 23:40:00  2624.255  2624.255  2624.255  2624.255
526173 2024-12-31 23:45:00  2624.255  2624.255  2624.255  2624.255
526174 2024-12-31 23:50:00  2624.255  2624.255  2624.255  2624.255
526175 2024-12-31 23:55:00  2624.255  2624.255  2624.255  2624.255

        trade_type_hammer  trade_result_hammer  tp_hammer  sl_hammer
0                       0                    0        NaN        NaN
1                       0                    0        NaN        NaN
2                       0                    0        NaN        NaN
3                       0                    0        NaN        NaN
4                       0                    0        NaN        NaN
...                   ...                  ...        ...        ...
526171                  0                    0        NaN        NaN
526172                  0                    0        NaN        NaN
526173                  0                    0        NaN        NaN
526174                  0                    0        NaN        NaN
526175                  0                    0        NaN        NaN

[526176 rows x 9 columns]

In [96]:
df = df[df['trade_type_hammer'] != 0]

In [97]:
df = df[['Gmt time','Open', 'High', 'Low', 'Close', 'trade_type_hammer', 'trade_result_hammer', 'tp_hammer', 'sl_hammer']]

In [98]:
df

,Gmt time,Open,High,Low,Close,trade_type_hammer,trade_result_hammer,tp_hammer,sl_hammer
310,2020-01-02 01:50:00,1519.300,1519.408,1518.875,1519.365,1,1,1519.981,1518.567
335,2020-01-02 03:55:00,1520.208,1520.298,1520.115,1520.275,1,1,1520.655,1519.925
399,2020-01-02 09:15:00,1519.995,1520.265,1519.515,1520.205,1,2,1520.671,1519.282
422,2020-01-02 11:10:00,1521.505,1521.555,1521.228,1521.375,1,2,1521.881,1520.975
496,2020-01-02 17:20:00,1524.685,1524.685,1522.715,1524.605,1,2,1527.385,1521.325
...,...,...,...,...,...,...,...,...,...
525997,2024-12-31 09:05:00,2615.464,2615.955,2614.385,2615.854,1,1,2617.634,2613.495
526016,2024-12-31 10:40:00,2611.825,2612.205,2611.395,2612.078,1,2,2613.658,2610.605
526073,2024-12-31 15:25:00,2617.475,2618.355,2616.935,2617.965,1,2,2620.325,2615.755
526104,2024-12-31 18:00:00,2624.135,2625.205,2623.115,2625.125,1,2,2626.485,2622.435
526123,2024-12-31 19:35:00,2623.875,2624.095,2623.245,2623.635,1,1,2625.535,2622.295

In [87]:
# حساب التكرارات والنسب المئوية
result = df['trade_result_hammer'].value_counts().sort_index()
percent = df['trade_result_hammer'].value_counts(normalize=True).sort_index() * 100

# دمج النتائج في DataFrame
result_df = pd.DataFrame({
    'Count': result,
    'Percentage (%)': percent.round(1)})

result_df['Percentage (%)'] = result_df['Percentage (%)'].astype(str) + '%'

print(result_df)

                     Count Percentage (%)
trade_result_hammer
1                     4705          49.9%
2                     4721          50.1%

In [88]:
import pandas as pd

# تصفية الصفقات التي تحتوي على نتائج
df = df[df['trade_result_hammer'] != 0]

# استخراج التاريخ فقط
df['Gmt date'] = df['Gmt time'].dt.date

# تصنيف الصفقات
df['trade_type'] = df['trade_result_hammer'].apply(lambda x: 'رابحة' if x == 2 else 'خاسرة')

# حساب عدد الصفقات لكل يوم
daily_trades = df.groupby(['Gmt date', 'trade_type']).size().unstack(fill_value=0)

# إعادة تسمية الأعمدة
daily_trades = daily_trades.rename(columns={'رابحة': 'Winning Trades', 'خاسرة': 'Losing Trades'})

# إنشاء نطاق تواريخ شامل من البيانات الأصلية
start_date = df['Gmt time'].min().normalize()
end_date = df['Gmt time'].max().normalize()
all_dates = pd.date_range(start=start_date, end=end_date, freq='D')

# تحويل الفهرس إلى تنسيق تاريخي
daily_trades.index = pd.to_datetime(daily_trades.index)

# إعادة الفهرس ليشمل جميع التواريخ
daily_trades = daily_trades.reindex(all_dates, fill_value=0)

# تصفية أيام السبت (5) والأحد (6) باستخدام weekday
daily_trades = daily_trades[daily_trades.index.weekday < 5]  # 0-4 = من الاثنين إلى الجمعة

# إضافة عمود الصفقات الكلية
daily_trades['Total Trades'] = daily_trades['Winning Trades'] + daily_trades['Losing Trades']

# إعادة تنسيق الفهرس لعرضه كتواريخ بدون وقت
daily_trades.index = daily_trades.index.date

print(daily_trades)

trade_type  Losing Trades  Winning Trades  Total Trades
2020-01-02              2               4             6
2020-01-03              3               6             9
2020-01-06              1               3             4
2020-01-07              4               6            10
2020-01-08              9               4            13
...                   ...             ...           ...
2024-12-25              0               1             1
2024-12-26              1               5             6
2024-12-27              3               7            10
2024-12-30              9               6            15
2024-12-31              5               5            10

[1304 rows x 3 columns]

In [89]:
daily_trades.describe().round(1).drop(['count','std'])

trade_type  Losing Trades  Winning Trades  Total Trades
mean                  3.6             3.6           7.1
min                   0.0             0.0           0.0
25%                   2.0             2.0           5.0
50%                   3.0             3.0           7.0
75%                   5.0             5.0           9.0
max                  12.0            12.0          17.0

In [95]:
daily_trades.to_csv(r"C:\Users\Access\Documents\AI\XAUUSD_5m_trade_result_hammer.csv", index=True)